// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_setting.sql

package sqlc

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT value FROM app_setting WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listSettings = `-- name: ListSettings :many
SELECT "key", value, updated_at FROM app_setting ORDER BY key
`

func (q *Queries) ListSettings(ctx context.Context) ([]AppSetting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSetting{}
	for rows.Next() {
		var i AppSetting
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSetting = `-- name: SetSetting :exec
INSERT INTO app_setting (key, value)
VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET
    value      = excluded.value,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

type SetSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) error {
	_, err := q.db.ExecContext(ctx, setSetting, arg.Key, arg.Value)
	return err
}
