// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bitbucket_repo.sql

package sqlc

import (
	"context"
)

const deleteBitbucketReposByAccount = `-- name: DeleteBitbucketReposByAccount :exec
DELETE FROM bitbucket_repo WHERE account_id = ?
`

func (q *Queries) DeleteBitbucketReposByAccount(ctx context.Context, accountID string) error {
	_, err := q.db.ExecContext(ctx, deleteBitbucketReposByAccount, accountID)
	return err
}

const listBitbucketRepos = `-- name: ListBitbucketRepos :many
SELECT id, account_id, workspace_uuid, external_id, name, full_name, private, selected, created_at FROM bitbucket_repo ORDER BY full_name
`

func (q *Queries) ListBitbucketRepos(ctx context.Context) ([]BitbucketRepo, error) {
	rows, err := q.db.QueryContext(ctx, listBitbucketRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BitbucketRepo{}
	for rows.Next() {
		var i BitbucketRepo
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.WorkspaceUuid,
			&i.ExternalID,
			&i.Name,
			&i.FullName,
			&i.Private,
			&i.Selected,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBitbucketReposByAccount = `-- name: ListBitbucketReposByAccount :many
SELECT id, account_id, workspace_uuid, external_id, name, full_name, private, selected, created_at FROM bitbucket_repo WHERE account_id = ? ORDER BY full_name
`

func (q *Queries) ListBitbucketReposByAccount(ctx context.Context, accountID string) ([]BitbucketRepo, error) {
	rows, err := q.db.QueryContext(ctx, listBitbucketReposByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BitbucketRepo{}
	for rows.Next() {
		var i BitbucketRepo
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.WorkspaceUuid,
			&i.ExternalID,
			&i.Name,
			&i.FullName,
			&i.Private,
			&i.Selected,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBitbucketRepoSelected = `-- name: SetBitbucketRepoSelected :exec
UPDATE bitbucket_repo SET selected = ? WHERE id = ?
`

type SetBitbucketRepoSelectedParams struct {
	Selected int64 `json:"selected"`
	ID       int64 `json:"id"`
}

func (q *Queries) SetBitbucketRepoSelected(ctx context.Context, arg SetBitbucketRepoSelectedParams) error {
	_, err := q.db.ExecContext(ctx, setBitbucketRepoSelected, arg.Selected, arg.ID)
	return err
}

const upsertBitbucketRepo = `-- name: UpsertBitbucketRepo :one
INSERT INTO bitbucket_repo (account_id, workspace_uuid, external_id, name, full_name, private, selected)
VALUES (?, ?, ?, ?, ?, ?, CASE WHEN ? = 1 THEN 1 ELSE 0 END)
ON CONFLICT (account_id, external_id) DO UPDATE SET
    workspace_uuid = excluded.workspace_uuid,
    name = excluded.name,
    full_name = excluded.full_name,
    private = excluded.private
RETURNING id, account_id, workspace_uuid, external_id, name, full_name, private, selected, created_at
`

type UpsertBitbucketRepoParams struct {
	AccountID     string      `json:"account_id"`
	WorkspaceUuid string      `json:"workspace_uuid"`
	ExternalID    string      `json:"external_id"`
	Name          string      `json:"name"`
	FullName      string      `json:"full_name"`
	Private       int64       `json:"private"`
	Column7       interface{} `json:"column_7"`
}

func (q *Queries) UpsertBitbucketRepo(ctx context.Context, arg UpsertBitbucketRepoParams) (BitbucketRepo, error) {
	row := q.db.QueryRowContext(ctx, upsertBitbucketRepo,
		arg.AccountID,
		arg.WorkspaceUuid,
		arg.ExternalID,
		arg.Name,
		arg.FullName,
		arg.Private,
		arg.Column7,
	)
	var i BitbucketRepo
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.WorkspaceUuid,
		&i.ExternalID,
		&i.Name,
		&i.FullName,
		&i.Private,
		&i.Selected,
		&i.CreatedAt,
	)
	return i, err
}
