// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bitbucket_workspace.sql

package sqlc

import (
	"context"
)

const deleteBitbucketWorkspacesByAccount = `-- name: DeleteBitbucketWorkspacesByAccount :exec
DELETE FROM bitbucket_workspace WHERE account_id = ?
`

func (q *Queries) DeleteBitbucketWorkspacesByAccount(ctx context.Context, accountID string) error {
	_, err := q.db.ExecContext(ctx, deleteBitbucketWorkspacesByAccount, accountID)
	return err
}

const listBitbucketWorkspaces = `-- name: ListBitbucketWorkspaces :many
SELECT id, account_id, external_id, slug, name, selected, created_at FROM bitbucket_workspace ORDER BY name
`

func (q *Queries) ListBitbucketWorkspaces(ctx context.Context) ([]BitbucketWorkspace, error) {
	rows, err := q.db.QueryContext(ctx, listBitbucketWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BitbucketWorkspace{}
	for rows.Next() {
		var i BitbucketWorkspace
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ExternalID,
			&i.Slug,
			&i.Name,
			&i.Selected,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBitbucketWorkspacesByAccount = `-- name: ListBitbucketWorkspacesByAccount :many
SELECT id, account_id, external_id, slug, name, selected, created_at FROM bitbucket_workspace WHERE account_id = ? ORDER BY name
`

func (q *Queries) ListBitbucketWorkspacesByAccount(ctx context.Context, accountID string) ([]BitbucketWorkspace, error) {
	rows, err := q.db.QueryContext(ctx, listBitbucketWorkspacesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BitbucketWorkspace{}
	for rows.Next() {
		var i BitbucketWorkspace
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ExternalID,
			&i.Slug,
			&i.Name,
			&i.Selected,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBitbucketWorkspaceSelected = `-- name: SetBitbucketWorkspaceSelected :exec
UPDATE bitbucket_workspace SET selected = ? WHERE id = ?
`

type SetBitbucketWorkspaceSelectedParams struct {
	Selected int64 `json:"selected"`
	ID       int64 `json:"id"`
}

func (q *Queries) SetBitbucketWorkspaceSelected(ctx context.Context, arg SetBitbucketWorkspaceSelectedParams) error {
	_, err := q.db.ExecContext(ctx, setBitbucketWorkspaceSelected, arg.Selected, arg.ID)
	return err
}

const upsertBitbucketWorkspace = `-- name: UpsertBitbucketWorkspace :one
INSERT INTO bitbucket_workspace (account_id, external_id, slug, name, selected)
VALUES (?, ?, ?, ?, CASE WHEN ? = 1 THEN 1 ELSE 0 END)
ON CONFLICT (account_id, external_id) DO UPDATE SET
    slug = excluded.slug,
    name = excluded.name
RETURNING id, account_id, external_id, slug, name, selected, created_at
`

type UpsertBitbucketWorkspaceParams struct {
	AccountID  string      `json:"account_id"`
	ExternalID string      `json:"external_id"`
	Slug       string      `json:"slug"`
	Name       string      `json:"name"`
	Column5    interface{} `json:"column_5"`
}

func (q *Queries) UpsertBitbucketWorkspace(ctx context.Context, arg UpsertBitbucketWorkspaceParams) (BitbucketWorkspace, error) {
	row := q.db.QueryRowContext(ctx, upsertBitbucketWorkspace,
		arg.AccountID,
		arg.ExternalID,
		arg.Slug,
		arg.Name,
		arg.Column5,
	)
	var i BitbucketWorkspace
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ExternalID,
		&i.Slug,
		&i.Name,
		&i.Selected,
		&i.CreatedAt,
	)
	return i, err
}
