// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getCalendarByProviderExternalID = `-- name: GetCalendarByProviderExternalID :one
SELECT id, provider, external_id, name, is_primary, selected, default_category_id, created_at FROM calendar WHERE provider = ? AND external_id = ?
`

type GetCalendarByProviderExternalIDParams struct {
	Provider   string `json:"provider"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) GetCalendarByProviderExternalID(ctx context.Context, arg GetCalendarByProviderExternalIDParams) (Calendar, error) {
	row := q.db.QueryRowContext(ctx, getCalendarByProviderExternalID, arg.Provider, arg.ExternalID)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ExternalID,
		&i.Name,
		&i.IsPrimary,
		&i.Selected,
		&i.DefaultCategoryID,
		&i.CreatedAt,
	)
	return i, err
}

const listCalendars = `-- name: ListCalendars :many
SELECT id, provider, external_id, name, is_primary, selected, default_category_id, created_at FROM calendar ORDER BY is_primary DESC, name
`

func (q *Queries) ListCalendars(ctx context.Context) ([]Calendar, error) {
	rows, err := q.db.QueryContext(ctx, listCalendars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Calendar{}
	for rows.Next() {
		var i Calendar
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ExternalID,
			&i.Name,
			&i.IsPrimary,
			&i.Selected,
			&i.DefaultCategoryID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSelectedCalendars = `-- name: ListSelectedCalendars :many
SELECT id, provider, external_id, name, is_primary, selected, default_category_id, created_at FROM calendar WHERE selected = 1 ORDER BY is_primary DESC, name
`

func (q *Queries) ListSelectedCalendars(ctx context.Context) ([]Calendar, error) {
	rows, err := q.db.QueryContext(ctx, listSelectedCalendars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Calendar{}
	for rows.Next() {
		var i Calendar
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ExternalID,
			&i.Name,
			&i.IsPrimary,
			&i.Selected,
			&i.DefaultCategoryID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCalendarDefaultCategory = `-- name: SetCalendarDefaultCategory :exec
UPDATE calendar SET default_category_id = ? WHERE id = ?
`

type SetCalendarDefaultCategoryParams struct {
	DefaultCategoryID sql.NullInt64 `json:"default_category_id"`
	ID                int64         `json:"id"`
}

func (q *Queries) SetCalendarDefaultCategory(ctx context.Context, arg SetCalendarDefaultCategoryParams) error {
	_, err := q.db.ExecContext(ctx, setCalendarDefaultCategory, arg.DefaultCategoryID, arg.ID)
	return err
}

const setCalendarSelected = `-- name: SetCalendarSelected :exec
UPDATE calendar SET selected = ? WHERE id = ?
`

type SetCalendarSelectedParams struct {
	Selected int64 `json:"selected"`
	ID       int64 `json:"id"`
}

func (q *Queries) SetCalendarSelected(ctx context.Context, arg SetCalendarSelectedParams) error {
	_, err := q.db.ExecContext(ctx, setCalendarSelected, arg.Selected, arg.ID)
	return err
}

const upsertCalendar = `-- name: UpsertCalendar :one
INSERT INTO calendar (provider, external_id, name, is_primary)
VALUES (?, ?, ?, ?)
ON CONFLICT (provider, external_id) DO UPDATE SET
    name = excluded.name,
    is_primary = excluded.is_primary
RETURNING id, provider, external_id, name, is_primary, selected, default_category_id, created_at
`

type UpsertCalendarParams struct {
	Provider   string `json:"provider"`
	ExternalID string `json:"external_id"`
	Name       string `json:"name"`
	IsPrimary  int64  `json:"is_primary"`
}

func (q *Queries) UpsertCalendar(ctx context.Context, arg UpsertCalendarParams) (Calendar, error) {
	row := q.db.QueryRowContext(ctx, upsertCalendar,
		arg.Provider,
		arg.ExternalID,
		arg.Name,
		arg.IsPrimary,
	)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ExternalID,
		&i.Name,
		&i.IsPrimary,
		&i.Selected,
		&i.DefaultCategoryID,
		&i.CreatedAt,
	)
	return i, err
}
