// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category.sql

package sqlc

import (
	"context"
)

const clearDefaultGap = `-- name: ClearDefaultGap :exec
UPDATE category SET is_default_gap = 0 WHERE is_default_gap = 1
`

func (q *Queries) ClearDefaultGap(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearDefaultGap)
	return err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO category (name, is_default_gap)
VALUES (?, ?)
RETURNING id, name, is_default_gap, created_at
`

type CreateCategoryParams struct {
	Name         string `json:"name"`
	IsDefaultGap int64  `json:"is_default_gap"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, arg.IsDefaultGap)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefaultGap,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM category WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, is_default_gap, created_at FROM category WHERE id = ?
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefaultGap,
		&i.CreatedAt,
	)
	return i, err
}

const getDefaultGapCategory = `-- name: GetDefaultGapCategory :one
SELECT id, name, is_default_gap, created_at FROM category WHERE is_default_gap = 1
`

func (q *Queries) GetDefaultGapCategory(ctx context.Context) (Category, error) {
	row := q.db.QueryRowContext(ctx, getDefaultGapCategory)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefaultGap,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, is_default_gap, created_at FROM category ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsDefaultGap,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameCategory = `-- name: RenameCategory :exec
UPDATE category SET name = ? WHERE id = ?
`

type RenameCategoryParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) RenameCategory(ctx context.Context, arg RenameCategoryParams) error {
	_, err := q.db.ExecContext(ctx, renameCategory, arg.Name, arg.ID)
	return err
}

const setDefaultGap = `-- name: SetDefaultGap :exec
UPDATE category SET is_default_gap = 1 WHERE id = ?
`

func (q *Queries) SetDefaultGap(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setDefaultGap, id)
	return err
}
