// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category.sql

package sqlc

import (
	"context"
	"database/sql"
)

const archiveCategory = `-- name: ArchiveCategory :one
UPDATE category
SET archived_at = ?, is_default_gap = 0
WHERE id = ?
RETURNING id, name, is_default_gap, created_at, description, "key", color, archived_at
`

type ArchiveCategoryParams struct {
	ArchivedAt sql.NullString `json:"archived_at"`
	ID         int64          `json:"id"`
}

func (q *Queries) ArchiveCategory(ctx context.Context, arg ArchiveCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, archiveCategory, arg.ArchivedAt, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefaultGap,
		&i.CreatedAt,
		&i.Description,
		&i.Key,
		&i.Color,
		&i.ArchivedAt,
	)
	return i, err
}

const clearDefaultGap = `-- name: ClearDefaultGap :exec
UPDATE category SET is_default_gap = 0 WHERE is_default_gap = 1
`

func (q *Queries) ClearDefaultGap(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearDefaultGap)
	return err
}

const countCalendarReferencesToCategory = `-- name: CountCalendarReferencesToCategory :one
SELECT COUNT(*) FROM calendar WHERE default_category_id = ?
`

func (q *Queries) CountCalendarReferencesToCategory(ctx context.Context, defaultCategoryID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCalendarReferencesToCategory, defaultCategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMemoryReferencesToCategory = `-- name: CountMemoryReferencesToCategory :one
SELECT COUNT(*) FROM memory WHERE category_id = ?
`

func (q *Queries) CountMemoryReferencesToCategory(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMemoryReferencesToCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOverlayReferencesToCategory = `-- name: CountOverlayReferencesToCategory :one
SELECT COUNT(*) FROM overlay WHERE category_id = ?
`

func (q *Queries) CountOverlayReferencesToCategory(ctx context.Context, categoryID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOverlayReferencesToCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTimeEntryReferencesToCategory = `-- name: CountTimeEntryReferencesToCategory :one
SELECT COUNT(*) FROM time_entry WHERE category_id = ?
`

func (q *Queries) CountTimeEntryReferencesToCategory(ctx context.Context, categoryID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTimeEntryReferencesToCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO category (name, description, key, is_default_gap, color)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, is_default_gap, created_at, description, "key", color, archived_at
`

type CreateCategoryParams struct {
	Name         string `json:"name"`
	Description  string `json:"description"`
	Key          string `json:"key"`
	IsDefaultGap int64  `json:"is_default_gap"`
	Color        string `json:"color"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.Name,
		arg.Description,
		arg.Key,
		arg.IsDefaultGap,
		arg.Color,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefaultGap,
		&i.CreatedAt,
		&i.Description,
		&i.Key,
		&i.Color,
		&i.ArchivedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM category WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, is_default_gap, created_at, description, "key", color, archived_at FROM category WHERE id = ?
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefaultGap,
		&i.CreatedAt,
		&i.Description,
		&i.Key,
		&i.Color,
		&i.ArchivedAt,
	)
	return i, err
}

const getCategoryByKey = `-- name: GetCategoryByKey :one
SELECT id, name, is_default_gap, created_at, description, "key", color, archived_at FROM category WHERE key = ? AND archived_at IS NULL
`

func (q *Queries) GetCategoryByKey(ctx context.Context, key string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByKey, key)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefaultGap,
		&i.CreatedAt,
		&i.Description,
		&i.Key,
		&i.Color,
		&i.ArchivedAt,
	)
	return i, err
}

const getDefaultGapCategory = `-- name: GetDefaultGapCategory :one
SELECT id, name, is_default_gap, created_at, description, "key", color, archived_at FROM category WHERE is_default_gap = 1 AND archived_at IS NULL
`

func (q *Queries) GetDefaultGapCategory(ctx context.Context) (Category, error) {
	row := q.db.QueryRowContext(ctx, getDefaultGapCategory)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefaultGap,
		&i.CreatedAt,
		&i.Description,
		&i.Key,
		&i.Color,
		&i.ArchivedAt,
	)
	return i, err
}

const listAllCategories = `-- name: ListAllCategories :many
SELECT id, name, is_default_gap, created_at, description, "key", color, archived_at FROM category ORDER BY name
`

func (q *Queries) ListAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsDefaultGap,
			&i.CreatedAt,
			&i.Description,
			&i.Key,
			&i.Color,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, is_default_gap, created_at, description, "key", color, archived_at FROM category WHERE archived_at IS NULL ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsDefaultGap,
			&i.CreatedAt,
			&i.Description,
			&i.Key,
			&i.Color,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultGap = `-- name: SetDefaultGap :exec
UPDATE category SET is_default_gap = 1 WHERE id = ?
`

func (q *Queries) SetDefaultGap(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setDefaultGap, id)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE category
SET name = ?, description = ?, key = ?, color = ?
WHERE id = ?
`

type UpdateCategoryParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Key         string `json:"key"`
	Color       string `json:"color"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory,
		arg.Name,
		arg.Description,
		arg.Key,
		arg.Color,
		arg.ID,
	)
	return err
}
