// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM event WHERE id = ?
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, period_id, calendar_id, google_event_id, instance_id, recurring_event_id, ical_uid, title, description, location, organizer, attendees, status, all_day, start_utc, end_utc, start_date, end_date, original_tz, active, source_hash, created_at, updated_at FROM event WHERE id = ?
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.CalendarID,
		&i.GoogleEventID,
		&i.InstanceID,
		&i.RecurringEventID,
		&i.IcalUid,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Organizer,
		&i.Attendees,
		&i.Status,
		&i.AllDay,
		&i.StartUtc,
		&i.EndUtc,
		&i.StartDate,
		&i.EndDate,
		&i.OriginalTz,
		&i.Active,
		&i.SourceHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllEventsForPeriod = `-- name: ListAllEventsForPeriod :many
SELECT id, period_id, calendar_id, google_event_id, instance_id, recurring_event_id, ical_uid, title, description, location, organizer, attendees, status, all_day, start_utc, end_utc, start_date, end_date, original_tz, active, source_hash, created_at, updated_at FROM event WHERE period_id = ? ORDER BY start_utc, start_date
`

func (q *Queries) ListAllEventsForPeriod(ctx context.Context, periodID int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listAllEventsForPeriod, periodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.CalendarID,
			&i.GoogleEventID,
			&i.InstanceID,
			&i.RecurringEventID,
			&i.IcalUid,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Organizer,
			&i.Attendees,
			&i.Status,
			&i.AllDay,
			&i.StartUtc,
			&i.EndUtc,
			&i.StartDate,
			&i.EndDate,
			&i.OriginalTz,
			&i.Active,
			&i.SourceHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByIcalUID = `-- name: ListEventsByIcalUID :many
SELECT id, period_id, calendar_id, google_event_id, instance_id, recurring_event_id, ical_uid, title, description, location, organizer, attendees, status, all_day, start_utc, end_utc, start_date, end_date, original_tz, active, source_hash, created_at, updated_at FROM event WHERE period_id = ? AND ical_uid = ? AND ical_uid <> ''
`

type ListEventsByIcalUIDParams struct {
	PeriodID int64  `json:"period_id"`
	IcalUid  string `json:"ical_uid"`
}

func (q *Queries) ListEventsByIcalUID(ctx context.Context, arg ListEventsByIcalUIDParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByIcalUID, arg.PeriodID, arg.IcalUid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.CalendarID,
			&i.GoogleEventID,
			&i.InstanceID,
			&i.RecurringEventID,
			&i.IcalUid,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Organizer,
			&i.Attendees,
			&i.Status,
			&i.AllDay,
			&i.StartUtc,
			&i.EndUtc,
			&i.StartDate,
			&i.EndDate,
			&i.OriginalTz,
			&i.Active,
			&i.SourceHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsForPeriod = `-- name: ListEventsForPeriod :many
SELECT id, period_id, calendar_id, google_event_id, instance_id, recurring_event_id, ical_uid, title, description, location, organizer, attendees, status, all_day, start_utc, end_utc, start_date, end_date, original_tz, active, source_hash, created_at, updated_at FROM event WHERE period_id = ? AND active = 1 ORDER BY start_utc, start_date
`

func (q *Queries) ListEventsForPeriod(ctx context.Context, periodID int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsForPeriod, periodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.CalendarID,
			&i.GoogleEventID,
			&i.InstanceID,
			&i.RecurringEventID,
			&i.IcalUid,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Organizer,
			&i.Attendees,
			&i.Status,
			&i.AllDay,
			&i.StartUtc,
			&i.EndUtc,
			&i.StartDate,
			&i.EndDate,
			&i.OriginalTz,
			&i.Active,
			&i.SourceHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEventActiveByCalendar = `-- name: SetEventActiveByCalendar :exec
UPDATE event SET active = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE calendar_id = ?
`

type SetEventActiveByCalendarParams struct {
	Active     int64 `json:"active"`
	CalendarID int64 `json:"calendar_id"`
}

// Soft-hide / restore all events from a calendar when it is deselected / reselected.
func (q *Queries) SetEventActiveByCalendar(ctx context.Context, arg SetEventActiveByCalendarParams) error {
	_, err := q.db.ExecContext(ctx, setEventActiveByCalendar, arg.Active, arg.CalendarID)
	return err
}

const upsertEvent = `-- name: UpsertEvent :one
INSERT INTO event (
    period_id, calendar_id, google_event_id, instance_id, recurring_event_id,
    ical_uid, title, description, location, organizer, attendees, status,
    all_day, start_utc, end_utc, start_date, end_date, original_tz, source_hash
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (period_id, calendar_id, google_event_id, instance_id) DO UPDATE SET
    recurring_event_id = excluded.recurring_event_id,
    ical_uid           = excluded.ical_uid,
    title              = excluded.title,
    description        = excluded.description,
    location           = excluded.location,
    organizer          = excluded.organizer,
    attendees          = excluded.attendees,
    status             = excluded.status,
    all_day            = excluded.all_day,
    start_utc          = excluded.start_utc,
    end_utc            = excluded.end_utc,
    start_date         = excluded.start_date,
    end_date           = excluded.end_date,
    original_tz        = excluded.original_tz,
    source_hash        = excluded.source_hash,
    updated_at         = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
RETURNING id, period_id, calendar_id, google_event_id, instance_id, recurring_event_id, ical_uid, title, description, location, organizer, attendees, status, all_day, start_utc, end_utc, start_date, end_date, original_tz, active, source_hash, created_at, updated_at
`

type UpsertEventParams struct {
	PeriodID         int64          `json:"period_id"`
	CalendarID       int64          `json:"calendar_id"`
	GoogleEventID    string         `json:"google_event_id"`
	InstanceID       string         `json:"instance_id"`
	RecurringEventID string         `json:"recurring_event_id"`
	IcalUid          string         `json:"ical_uid"`
	Title            string         `json:"title"`
	Description      string         `json:"description"`
	Location         string         `json:"location"`
	Organizer        string         `json:"organizer"`
	Attendees        string         `json:"attendees"`
	Status           string         `json:"status"`
	AllDay           int64          `json:"all_day"`
	StartUtc         sql.NullString `json:"start_utc"`
	EndUtc           sql.NullString `json:"end_utc"`
	StartDate        sql.NullString `json:"start_date"`
	EndDate          sql.NullString `json:"end_date"`
	OriginalTz       string         `json:"original_tz"`
	SourceHash       string         `json:"source_hash"`
}

// Re-sync entry point: insert a fact, or update mutable synced fields on re-pull.
// Never touches user decisions (those live in overlay), and preserves `active`.
func (q *Queries) UpsertEvent(ctx context.Context, arg UpsertEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, upsertEvent,
		arg.PeriodID,
		arg.CalendarID,
		arg.GoogleEventID,
		arg.InstanceID,
		arg.RecurringEventID,
		arg.IcalUid,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Organizer,
		arg.Attendees,
		arg.Status,
		arg.AllDay,
		arg.StartUtc,
		arg.EndUtc,
		arg.StartDate,
		arg.EndDate,
		arg.OriginalTz,
		arg.SourceHash,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.CalendarID,
		&i.GoogleEventID,
		&i.InstanceID,
		&i.RecurringEventID,
		&i.IcalUid,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Organizer,
		&i.Attendees,
		&i.Status,
		&i.AllDay,
		&i.StartUtc,
		&i.EndUtc,
		&i.StartDate,
		&i.EndDate,
		&i.OriginalTz,
		&i.Active,
		&i.SourceHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
