// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: export_template.sql

package sqlc

import (
	"context"
)

const createExportTemplate = `-- name: CreateExportTemplate :one
INSERT INTO export_template (key, name, description, format, builtin, body)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, "key", name, description, format, builtin, body, created_at
`

type CreateExportTemplateParams struct {
	Key         string `json:"key"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Format      string `json:"format"`
	Builtin     int64  `json:"builtin"`
	Body        string `json:"body"`
}

func (q *Queries) CreateExportTemplate(ctx context.Context, arg CreateExportTemplateParams) (ExportTemplate, error) {
	row := q.db.QueryRowContext(ctx, createExportTemplate,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Format,
		arg.Builtin,
		arg.Body,
	)
	var i ExportTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Format,
		&i.Builtin,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExportTemplate = `-- name: DeleteExportTemplate :execrows
DELETE FROM export_template WHERE id = ? AND builtin = 0
`

func (q *Queries) DeleteExportTemplate(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExportTemplate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const exportTemplateKeyExists = `-- name: ExportTemplateKeyExists :one
SELECT COUNT(*) FROM export_template WHERE key = ?
`

func (q *Queries) ExportTemplateKeyExists(ctx context.Context, key string) (int64, error) {
	row := q.db.QueryRowContext(ctx, exportTemplateKeyExists, key)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getExportTemplate = `-- name: GetExportTemplate :one
SELECT id, "key", name, description, format, builtin, body, created_at FROM export_template WHERE id = ?
`

func (q *Queries) GetExportTemplate(ctx context.Context, id int64) (ExportTemplate, error) {
	row := q.db.QueryRowContext(ctx, getExportTemplate, id)
	var i ExportTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Format,
		&i.Builtin,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getExportTemplateByKey = `-- name: GetExportTemplateByKey :one
SELECT id, "key", name, description, format, builtin, body, created_at FROM export_template WHERE key = ?
`

func (q *Queries) GetExportTemplateByKey(ctx context.Context, key string) (ExportTemplate, error) {
	row := q.db.QueryRowContext(ctx, getExportTemplateByKey, key)
	var i ExportTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Format,
		&i.Builtin,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listExportTemplates = `-- name: ListExportTemplates :many
SELECT id, "key", name, description, format, builtin, body, created_at FROM export_template ORDER BY builtin DESC, name
`

func (q *Queries) ListExportTemplates(ctx context.Context) ([]ExportTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listExportTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportTemplate{}
	for rows.Next() {
		var i ExportTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Format,
			&i.Builtin,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExportTemplate = `-- name: UpdateExportTemplate :one
UPDATE export_template
SET name = ?, description = ?, format = ?, body = ?
WHERE id = ? AND builtin = 0
RETURNING id, "key", name, description, format, builtin, body, created_at
`

type UpdateExportTemplateParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Format      string `json:"format"`
	Body        string `json:"body"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateExportTemplate(ctx context.Context, arg UpdateExportTemplateParams) (ExportTemplate, error) {
	row := q.db.QueryRowContext(ctx, updateExportTemplate,
		arg.Name,
		arg.Description,
		arg.Format,
		arg.Body,
		arg.ID,
	)
	var i ExportTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Format,
		&i.Builtin,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}
