// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gap_fill.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createGapFill = `-- name: CreateGapFill :one
INSERT INTO gap_fill (period_id, day, start_utc, end_utc, category_id, note, source)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, period_id, day, start_utc, end_utc, category_id, note, source, created_at, updated_at
`

type CreateGapFillParams struct {
	PeriodID   int64         `json:"period_id"`
	Day        string        `json:"day"`
	StartUtc   string        `json:"start_utc"`
	EndUtc     string        `json:"end_utc"`
	CategoryID sql.NullInt64 `json:"category_id"`
	Note       string        `json:"note"`
	Source     string        `json:"source"`
}

func (q *Queries) CreateGapFill(ctx context.Context, arg CreateGapFillParams) (GapFill, error) {
	row := q.db.QueryRowContext(ctx, createGapFill,
		arg.PeriodID,
		arg.Day,
		arg.StartUtc,
		arg.EndUtc,
		arg.CategoryID,
		arg.Note,
		arg.Source,
	)
	var i GapFill
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.Day,
		&i.StartUtc,
		&i.EndUtc,
		&i.CategoryID,
		&i.Note,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGapFill = `-- name: DeleteGapFill :exec
DELETE FROM gap_fill WHERE id = ?
`

func (q *Queries) DeleteGapFill(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGapFill, id)
	return err
}

const listGapFillsForDay = `-- name: ListGapFillsForDay :many
SELECT id, period_id, day, start_utc, end_utc, category_id, note, source, created_at, updated_at FROM gap_fill WHERE period_id = ? AND day = ? ORDER BY start_utc
`

type ListGapFillsForDayParams struct {
	PeriodID int64  `json:"period_id"`
	Day      string `json:"day"`
}

func (q *Queries) ListGapFillsForDay(ctx context.Context, arg ListGapFillsForDayParams) ([]GapFill, error) {
	rows, err := q.db.QueryContext(ctx, listGapFillsForDay, arg.PeriodID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GapFill{}
	for rows.Next() {
		var i GapFill
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.Day,
			&i.StartUtc,
			&i.EndUtc,
			&i.CategoryID,
			&i.Note,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGapFillsForPeriod = `-- name: ListGapFillsForPeriod :many
SELECT id, period_id, day, start_utc, end_utc, category_id, note, source, created_at, updated_at FROM gap_fill WHERE period_id = ? ORDER BY day, start_utc
`

func (q *Queries) ListGapFillsForPeriod(ctx context.Context, periodID int64) ([]GapFill, error) {
	rows, err := q.db.QueryContext(ctx, listGapFillsForPeriod, periodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GapFill{}
	for rows.Next() {
		var i GapFill
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.Day,
			&i.StartUtc,
			&i.EndUtc,
			&i.CategoryID,
			&i.Note,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGapFill = `-- name: UpdateGapFill :exec
UPDATE gap_fill SET
    start_utc   = ?,
    end_utc     = ?,
    category_id = ?,
    note        = ?,
    updated_at  = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateGapFillParams struct {
	StartUtc   string        `json:"start_utc"`
	EndUtc     string        `json:"end_utc"`
	CategoryID sql.NullInt64 `json:"category_id"`
	Note       string        `json:"note"`
	ID         int64         `json:"id"`
}

func (q *Queries) UpdateGapFill(ctx context.Context, arg UpdateGapFillParams) error {
	_, err := q.db.ExecContext(ctx, updateGapFill,
		arg.StartUtc,
		arg.EndUtc,
		arg.CategoryID,
		arg.Note,
		arg.ID,
	)
	return err
}
