// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github_repo.sql

package sqlc

import (
	"context"
)

const deleteGitHubReposByAccount = `-- name: DeleteGitHubReposByAccount :exec
DELETE FROM github_repo WHERE account_id = ?
`

func (q *Queries) DeleteGitHubReposByAccount(ctx context.Context, accountID string) error {
	_, err := q.db.ExecContext(ctx, deleteGitHubReposByAccount, accountID)
	return err
}

const getGitHubRepo = `-- name: GetGitHubRepo :one
SELECT id, account_id, external_id, name, full_name, private, selected, created_at FROM github_repo WHERE id = ?
`

func (q *Queries) GetGitHubRepo(ctx context.Context, id int64) (GithubRepo, error) {
	row := q.db.QueryRowContext(ctx, getGitHubRepo, id)
	var i GithubRepo
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ExternalID,
		&i.Name,
		&i.FullName,
		&i.Private,
		&i.Selected,
		&i.CreatedAt,
	)
	return i, err
}

const listGitHubRepos = `-- name: ListGitHubRepos :many
SELECT id, account_id, external_id, name, full_name, private, selected, created_at FROM github_repo ORDER BY full_name
`

func (q *Queries) ListGitHubRepos(ctx context.Context) ([]GithubRepo, error) {
	rows, err := q.db.QueryContext(ctx, listGitHubRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubRepo{}
	for rows.Next() {
		var i GithubRepo
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ExternalID,
			&i.Name,
			&i.FullName,
			&i.Private,
			&i.Selected,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitHubReposByAccount = `-- name: ListGitHubReposByAccount :many
SELECT id, account_id, external_id, name, full_name, private, selected, created_at FROM github_repo WHERE account_id = ? ORDER BY full_name
`

func (q *Queries) ListGitHubReposByAccount(ctx context.Context, accountID string) ([]GithubRepo, error) {
	rows, err := q.db.QueryContext(ctx, listGitHubReposByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubRepo{}
	for rows.Next() {
		var i GithubRepo
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ExternalID,
			&i.Name,
			&i.FullName,
			&i.Private,
			&i.Selected,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSelectedGitHubRepos = `-- name: ListSelectedGitHubRepos :many
SELECT id, account_id, external_id, name, full_name, private, selected, created_at FROM github_repo WHERE selected = 1 ORDER BY full_name
`

func (q *Queries) ListSelectedGitHubRepos(ctx context.Context) ([]GithubRepo, error) {
	rows, err := q.db.QueryContext(ctx, listSelectedGitHubRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubRepo{}
	for rows.Next() {
		var i GithubRepo
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ExternalID,
			&i.Name,
			&i.FullName,
			&i.Private,
			&i.Selected,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGitHubRepoSelected = `-- name: SetGitHubRepoSelected :exec
UPDATE github_repo SET selected = ? WHERE id = ?
`

type SetGitHubRepoSelectedParams struct {
	Selected int64 `json:"selected"`
	ID       int64 `json:"id"`
}

func (q *Queries) SetGitHubRepoSelected(ctx context.Context, arg SetGitHubRepoSelectedParams) error {
	_, err := q.db.ExecContext(ctx, setGitHubRepoSelected, arg.Selected, arg.ID)
	return err
}

const upsertGitHubRepo = `-- name: UpsertGitHubRepo :one
INSERT INTO github_repo (account_id, external_id, name, full_name, private, selected)
VALUES (?, ?, ?, ?, ?, CASE WHEN ? = 1 THEN 1 ELSE 0 END)
ON CONFLICT (account_id, external_id) DO UPDATE SET
    name = excluded.name,
    full_name = excluded.full_name,
    private = excluded.private
RETURNING id, account_id, external_id, name, full_name, private, selected, created_at
`

type UpsertGitHubRepoParams struct {
	AccountID  string      `json:"account_id"`
	ExternalID string      `json:"external_id"`
	Name       string      `json:"name"`
	FullName   string      `json:"full_name"`
	Private    int64       `json:"private"`
	Column6    interface{} `json:"column_6"`
}

func (q *Queries) UpsertGitHubRepo(ctx context.Context, arg UpsertGitHubRepoParams) (GithubRepo, error) {
	row := q.db.QueryRowContext(ctx, upsertGitHubRepo,
		arg.AccountID,
		arg.ExternalID,
		arg.Name,
		arg.FullName,
		arg.Private,
		arg.Column6,
	)
	var i GithubRepo
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ExternalID,
		&i.Name,
		&i.FullName,
		&i.Private,
		&i.Selected,
		&i.CreatedAt,
	)
	return i, err
}
