// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integration_connection.sql

package sqlc

import (
	"context"
)

const deleteIntegrationConnection = `-- name: DeleteIntegrationConnection :exec
DELETE FROM integration_connection
WHERE provider = ? AND account_id = ?
`

type DeleteIntegrationConnectionParams struct {
	Provider  string `json:"provider"`
	AccountID string `json:"account_id"`
}

func (q *Queries) DeleteIntegrationConnection(ctx context.Context, arg DeleteIntegrationConnectionParams) error {
	_, err := q.db.ExecContext(ctx, deleteIntegrationConnection, arg.Provider, arg.AccountID)
	return err
}

const getIntegrationConnection = `-- name: GetIntegrationConnection :one
SELECT id, provider, account_label, account_id, scopes, status, connected_at, updated_at
FROM integration_connection
WHERE provider = ? AND account_id = ?
`

type GetIntegrationConnectionParams struct {
	Provider  string `json:"provider"`
	AccountID string `json:"account_id"`
}

func (q *Queries) GetIntegrationConnection(ctx context.Context, arg GetIntegrationConnectionParams) (IntegrationConnection, error) {
	row := q.db.QueryRowContext(ctx, getIntegrationConnection, arg.Provider, arg.AccountID)
	var i IntegrationConnection
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.AccountLabel,
		&i.AccountID,
		&i.Scopes,
		&i.Status,
		&i.ConnectedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIntegrationConnections = `-- name: ListIntegrationConnections :many
SELECT id, provider, account_label, account_id, scopes, status, connected_at, updated_at
FROM integration_connection
ORDER BY provider, account_label
`

func (q *Queries) ListIntegrationConnections(ctx context.Context) ([]IntegrationConnection, error) {
	rows, err := q.db.QueryContext(ctx, listIntegrationConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegrationConnection{}
	for rows.Next() {
		var i IntegrationConnection
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.AccountLabel,
			&i.AccountID,
			&i.Scopes,
			&i.Status,
			&i.ConnectedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationConnectionsByProvider = `-- name: ListIntegrationConnectionsByProvider :many
SELECT id, provider, account_label, account_id, scopes, status, connected_at, updated_at
FROM integration_connection
WHERE provider = ?
ORDER BY account_label
`

func (q *Queries) ListIntegrationConnectionsByProvider(ctx context.Context, provider string) ([]IntegrationConnection, error) {
	rows, err := q.db.QueryContext(ctx, listIntegrationConnectionsByProvider, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegrationConnection{}
	for rows.Next() {
		var i IntegrationConnection
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.AccountLabel,
			&i.AccountID,
			&i.Scopes,
			&i.Status,
			&i.ConnectedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIntegrationConnectionStatus = `-- name: UpdateIntegrationConnectionStatus :exec
UPDATE integration_connection
SET status = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE provider = ? AND account_id = ?
`

type UpdateIntegrationConnectionStatusParams struct {
	Status    string `json:"status"`
	Provider  string `json:"provider"`
	AccountID string `json:"account_id"`
}

func (q *Queries) UpdateIntegrationConnectionStatus(ctx context.Context, arg UpdateIntegrationConnectionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateIntegrationConnectionStatus, arg.Status, arg.Provider, arg.AccountID)
	return err
}

const upsertIntegrationConnection = `-- name: UpsertIntegrationConnection :one
INSERT INTO integration_connection (
    provider, account_label, account_id, scopes, status, connected_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
)
ON CONFLICT (provider, account_id) DO UPDATE SET
    account_label = excluded.account_label,
    scopes        = excluded.scopes,
    status        = excluded.status,
    updated_at    = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
RETURNING id, provider, account_label, account_id, scopes, status, connected_at, updated_at
`

type UpsertIntegrationConnectionParams struct {
	Provider     string `json:"provider"`
	AccountLabel string `json:"account_label"`
	AccountID    string `json:"account_id"`
	Scopes       string `json:"scopes"`
	Status       string `json:"status"`
}

func (q *Queries) UpsertIntegrationConnection(ctx context.Context, arg UpsertIntegrationConnectionParams) (IntegrationConnection, error) {
	row := q.db.QueryRowContext(ctx, upsertIntegrationConnection,
		arg.Provider,
		arg.AccountLabel,
		arg.AccountID,
		arg.Scopes,
		arg.Status,
	)
	var i IntegrationConnection
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.AccountLabel,
		&i.AccountID,
		&i.Scopes,
		&i.Status,
		&i.ConnectedAt,
		&i.UpdatedAt,
	)
	return i, err
}
