// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memory.sql

package sqlc

import (
	"context"
)

const forgetMemory = `-- name: ForgetMemory :exec
DELETE FROM memory WHERE match_key = ?
`

func (q *Queries) ForgetMemory(ctx context.Context, matchKey string) error {
	_, err := q.db.ExecContext(ctx, forgetMemory, matchKey)
	return err
}

const getMemory = `-- name: GetMemory :one
SELECT match_key, category_id, hits, updated_at FROM memory WHERE match_key = ?
`

func (q *Queries) GetMemory(ctx context.Context, matchKey string) (Memory, error) {
	row := q.db.QueryRowContext(ctx, getMemory, matchKey)
	var i Memory
	err := row.Scan(
		&i.MatchKey,
		&i.CategoryID,
		&i.Hits,
		&i.UpdatedAt,
	)
	return i, err
}

const listMemory = `-- name: ListMemory :many
SELECT match_key, category_id, hits, updated_at FROM memory ORDER BY hits DESC
`

func (q *Queries) ListMemory(ctx context.Context) ([]Memory, error) {
	rows, err := q.db.QueryContext(ctx, listMemory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memory{}
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.MatchKey,
			&i.CategoryID,
			&i.Hits,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rememberCategory = `-- name: RememberCategory :one
INSERT INTO memory (match_key, category_id, hits)
VALUES (?, ?, 1)
ON CONFLICT (match_key) DO UPDATE SET
    category_id = excluded.category_id,
    hits        = memory.hits + 1,
    updated_at  = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
RETURNING match_key, category_id, hits, updated_at
`

type RememberCategoryParams struct {
	MatchKey   string `json:"match_key"`
	CategoryID int64  `json:"category_id"`
}

// Train memory from a user correction; bump hit count on repeat.
func (q *Queries) RememberCategory(ctx context.Context, arg RememberCategoryParams) (Memory, error) {
	row := q.db.QueryRowContext(ctx, rememberCategory, arg.MatchKey, arg.CategoryID)
	var i Memory
	err := row.Scan(
		&i.MatchKey,
		&i.CategoryID,
		&i.Hits,
		&i.UpdatedAt,
	)
	return i, err
}
