// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type AppSetting struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type Calendar struct {
	ID                int64         `json:"id"`
	Provider          string        `json:"provider"`
	ExternalID        string        `json:"external_id"`
	Name              string        `json:"name"`
	IsPrimary         int64         `json:"is_primary"`
	Selected          int64         `json:"selected"`
	DefaultCategoryID sql.NullInt64 `json:"default_category_id"`
	CreatedAt         string        `json:"created_at"`
}

type Category struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	IsDefaultGap int64  `json:"is_default_gap"`
	CreatedAt    string `json:"created_at"`
}

type Event struct {
	ID               int64          `json:"id"`
	PeriodID         int64          `json:"period_id"`
	CalendarID       int64          `json:"calendar_id"`
	Provider         string         `json:"provider"`
	ExternalID       string         `json:"external_id"`
	InstanceID       string         `json:"instance_id"`
	RecurringEventID string         `json:"recurring_event_id"`
	IcalUid          string         `json:"ical_uid"`
	Title            string         `json:"title"`
	Description      string         `json:"description"`
	Location         string         `json:"location"`
	Organizer        string         `json:"organizer"`
	Attendees        string         `json:"attendees"`
	Status           string         `json:"status"`
	AllDay           int64          `json:"all_day"`
	StartUtc         sql.NullString `json:"start_utc"`
	EndUtc           sql.NullString `json:"end_utc"`
	StartDate        sql.NullString `json:"start_date"`
	EndDate          sql.NullString `json:"end_date"`
	OriginalTz       string         `json:"original_tz"`
	Active           int64          `json:"active"`
	SourceHash       string         `json:"source_hash"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type GapFill struct {
	ID         int64         `json:"id"`
	PeriodID   int64         `json:"period_id"`
	Day        string        `json:"day"`
	StartUtc   string        `json:"start_utc"`
	EndUtc     string        `json:"end_utc"`
	CategoryID sql.NullInt64 `json:"category_id"`
	Note       string        `json:"note"`
	Source     string        `json:"source"`
	CreatedAt  string        `json:"created_at"`
	UpdatedAt  string        `json:"updated_at"`
}

type IntegrationConnection struct {
	ID           int64  `json:"id"`
	Provider     string `json:"provider"`
	AccountLabel string `json:"account_label"`
	AccountID    string `json:"account_id"`
	Scopes       string `json:"scopes"`
	Status       string `json:"status"`
	ConnectedAt  string `json:"connected_at"`
	UpdatedAt    string `json:"updated_at"`
}

type Memory struct {
	MatchKey   string `json:"match_key"`
	CategoryID int64  `json:"category_id"`
	Hits       int64  `json:"hits"`
	UpdatedAt  string `json:"updated_at"`
}

type Overlay struct {
	ID              int64          `json:"id"`
	PeriodID        int64          `json:"period_id"`
	Provider        string         `json:"provider"`
	ExternalID      string         `json:"external_id"`
	InstanceID      string         `json:"instance_id"`
	CategoryID      sql.NullInt64  `json:"category_id"`
	ResolvedOverlap sql.NullString `json:"resolved_overlap"`
	Note            string         `json:"note"`
	Kind            string         `json:"kind"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

type Period struct {
	ID                int64          `json:"id"`
	StartDate         string         `json:"start_date"`
	EndDate           string         `json:"end_date"`
	Cadence           string         `json:"cadence"`
	AnchorDate        string         `json:"anchor_date"`
	TargetHoursPerDay float64        `json:"target_hours_per_day"`
	LastSyncedAt      sql.NullString `json:"last_synced_at"`
	CreatedAt         string         `json:"created_at"`
}

type ReviewItem struct {
	ID         int64          `json:"id"`
	PeriodID   int64          `json:"period_id"`
	Kind       string         `json:"kind"`
	EventID    sql.NullInt64  `json:"event_id"`
	Payload    string         `json:"payload"`
	Status     string         `json:"status"`
	CreatedAt  string         `json:"created_at"`
	ResolvedAt sql.NullString `json:"resolved_at"`
}

type Submission struct {
	ID          int64  `json:"id"`
	PeriodID    int64  `json:"period_id"`
	Version     int64  `json:"version"`
	FinalizedAt string `json:"finalized_at"`
	FrozenBlob  string `json:"frozen_blob"`
}

type TzSegment struct {
	ID                int64  `json:"id"`
	PeriodID          int64  `json:"period_id"`
	EffectiveFromDate string `json:"effective_from_date"`
	IanaTz            string `json:"iana_tz"`
}
