// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: overlay.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteOverlay = `-- name: DeleteOverlay :exec
DELETE FROM overlay WHERE id = ?
`

func (q *Queries) DeleteOverlay(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteOverlay, id)
	return err
}

const getOverlay = `-- name: GetOverlay :one
SELECT id, period_id, provider, external_id, instance_id, category_id, resolved_overlap, note, kind, created_at, updated_at FROM overlay
WHERE period_id = ? AND provider = ? AND external_id = ? AND instance_id = ? AND kind = ?
`

type GetOverlayParams struct {
	PeriodID   int64  `json:"period_id"`
	Provider   string `json:"provider"`
	ExternalID string `json:"external_id"`
	InstanceID string `json:"instance_id"`
	Kind       string `json:"kind"`
}

func (q *Queries) GetOverlay(ctx context.Context, arg GetOverlayParams) (Overlay, error) {
	row := q.db.QueryRowContext(ctx, getOverlay,
		arg.PeriodID,
		arg.Provider,
		arg.ExternalID,
		arg.InstanceID,
		arg.Kind,
	)
	var i Overlay
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.Provider,
		&i.ExternalID,
		&i.InstanceID,
		&i.CategoryID,
		&i.ResolvedOverlap,
		&i.Note,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOverlaysForPeriod = `-- name: ListOverlaysForPeriod :many
SELECT id, period_id, provider, external_id, instance_id, category_id, resolved_overlap, note, kind, created_at, updated_at FROM overlay WHERE period_id = ?
`

func (q *Queries) ListOverlaysForPeriod(ctx context.Context, periodID int64) ([]Overlay, error) {
	rows, err := q.db.QueryContext(ctx, listOverlaysForPeriod, periodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Overlay{}
	for rows.Next() {
		var i Overlay
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.Provider,
			&i.ExternalID,
			&i.InstanceID,
			&i.CategoryID,
			&i.ResolvedOverlap,
			&i.Note,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOverlay = `-- name: UpsertOverlay :one
INSERT INTO overlay (
    period_id, provider, external_id, instance_id, category_id, resolved_overlap, note, kind
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (period_id, provider, external_id, instance_id, kind) DO UPDATE SET
    category_id      = excluded.category_id,
    resolved_overlap = excluded.resolved_overlap,
    note             = excluded.note,
    updated_at       = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
RETURNING id, period_id, provider, external_id, instance_id, category_id, resolved_overlap, note, kind, created_at, updated_at
`

type UpsertOverlayParams struct {
	PeriodID        int64          `json:"period_id"`
	Provider        string         `json:"provider"`
	ExternalID      string         `json:"external_id"`
	InstanceID      string         `json:"instance_id"`
	CategoryID      sql.NullInt64  `json:"category_id"`
	ResolvedOverlap sql.NullString `json:"resolved_overlap"`
	Note            string         `json:"note"`
	Kind            string         `json:"kind"`
}

func (q *Queries) UpsertOverlay(ctx context.Context, arg UpsertOverlayParams) (Overlay, error) {
	row := q.db.QueryRowContext(ctx, upsertOverlay,
		arg.PeriodID,
		arg.Provider,
		arg.ExternalID,
		arg.InstanceID,
		arg.CategoryID,
		arg.ResolvedOverlap,
		arg.Note,
		arg.Kind,
	)
	var i Overlay
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.Provider,
		&i.ExternalID,
		&i.InstanceID,
		&i.CategoryID,
		&i.ResolvedOverlap,
		&i.Note,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
