// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: period.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createPeriod = `-- name: CreatePeriod :one
INSERT INTO period (start_date, end_date, cadence, anchor_date, target_hours_per_day)
VALUES (?, ?, ?, ?, ?)
RETURNING id, start_date, end_date, cadence, anchor_date, target_hours_per_day, last_synced_at, created_at
`

type CreatePeriodParams struct {
	StartDate         string  `json:"start_date"`
	EndDate           string  `json:"end_date"`
	Cadence           string  `json:"cadence"`
	AnchorDate        string  `json:"anchor_date"`
	TargetHoursPerDay float64 `json:"target_hours_per_day"`
}

func (q *Queries) CreatePeriod(ctx context.Context, arg CreatePeriodParams) (Period, error) {
	row := q.db.QueryRowContext(ctx, createPeriod,
		arg.StartDate,
		arg.EndDate,
		arg.Cadence,
		arg.AnchorDate,
		arg.TargetHoursPerDay,
	)
	var i Period
	err := row.Scan(
		&i.ID,
		&i.StartDate,
		&i.EndDate,
		&i.Cadence,
		&i.AnchorDate,
		&i.TargetHoursPerDay,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deletePeriod = `-- name: DeletePeriod :exec
DELETE FROM period WHERE id = ?
`

func (q *Queries) DeletePeriod(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePeriod, id)
	return err
}

const deleteTzSegment = `-- name: DeleteTzSegment :exec
DELETE FROM tz_segment WHERE id = ?
`

func (q *Queries) DeleteTzSegment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTzSegment, id)
	return err
}

const getPeriod = `-- name: GetPeriod :one
SELECT id, start_date, end_date, cadence, anchor_date, target_hours_per_day, last_synced_at, created_at FROM period WHERE id = ?
`

func (q *Queries) GetPeriod(ctx context.Context, id int64) (Period, error) {
	row := q.db.QueryRowContext(ctx, getPeriod, id)
	var i Period
	err := row.Scan(
		&i.ID,
		&i.StartDate,
		&i.EndDate,
		&i.Cadence,
		&i.AnchorDate,
		&i.TargetHoursPerDay,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPeriodByRange = `-- name: GetPeriodByRange :one
SELECT id, start_date, end_date, cadence, anchor_date, target_hours_per_day, last_synced_at, created_at FROM period WHERE start_date = ? AND end_date = ?
`

type GetPeriodByRangeParams struct {
	StartDate string `json:"start_date"`
	EndDate   string `json:"end_date"`
}

func (q *Queries) GetPeriodByRange(ctx context.Context, arg GetPeriodByRangeParams) (Period, error) {
	row := q.db.QueryRowContext(ctx, getPeriodByRange, arg.StartDate, arg.EndDate)
	var i Period
	err := row.Scan(
		&i.ID,
		&i.StartDate,
		&i.EndDate,
		&i.Cadence,
		&i.AnchorDate,
		&i.TargetHoursPerDay,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPeriods = `-- name: ListPeriods :many
SELECT id, start_date, end_date, cadence, anchor_date, target_hours_per_day, last_synced_at, created_at FROM period ORDER BY start_date DESC
`

func (q *Queries) ListPeriods(ctx context.Context) ([]Period, error) {
	rows, err := q.db.QueryContext(ctx, listPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Period{}
	for rows.Next() {
		var i Period
		if err := rows.Scan(
			&i.ID,
			&i.StartDate,
			&i.EndDate,
			&i.Cadence,
			&i.AnchorDate,
			&i.TargetHoursPerDay,
			&i.LastSyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTzSegments = `-- name: ListTzSegments :many
SELECT id, period_id, effective_from_date, iana_tz FROM tz_segment WHERE period_id = ? ORDER BY effective_from_date
`

func (q *Queries) ListTzSegments(ctx context.Context, periodID int64) ([]TzSegment, error) {
	rows, err := q.db.QueryContext(ctx, listTzSegments, periodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TzSegment{}
	for rows.Next() {
		var i TzSegment
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.EffectiveFromDate,
			&i.IanaTz,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchPeriodSynced = `-- name: TouchPeriodSynced :exec
UPDATE period SET last_synced_at = ? WHERE id = ?
`

type TouchPeriodSyncedParams struct {
	LastSyncedAt sql.NullString `json:"last_synced_at"`
	ID           int64          `json:"id"`
}

func (q *Queries) TouchPeriodSynced(ctx context.Context, arg TouchPeriodSyncedParams) error {
	_, err := q.db.ExecContext(ctx, touchPeriodSynced, arg.LastSyncedAt, arg.ID)
	return err
}

const updatePeriodTarget = `-- name: UpdatePeriodTarget :exec
UPDATE period SET target_hours_per_day = ? WHERE id = ?
`

type UpdatePeriodTargetParams struct {
	TargetHoursPerDay float64 `json:"target_hours_per_day"`
	ID                int64   `json:"id"`
}

func (q *Queries) UpdatePeriodTarget(ctx context.Context, arg UpdatePeriodTargetParams) error {
	_, err := q.db.ExecContext(ctx, updatePeriodTarget, arg.TargetHoursPerDay, arg.ID)
	return err
}

const upsertTzSegment = `-- name: UpsertTzSegment :one
INSERT INTO tz_segment (period_id, effective_from_date, iana_tz)
VALUES (?, ?, ?)
ON CONFLICT (period_id, effective_from_date) DO UPDATE SET iana_tz = excluded.iana_tz
RETURNING id, period_id, effective_from_date, iana_tz
`

type UpsertTzSegmentParams struct {
	PeriodID          int64  `json:"period_id"`
	EffectiveFromDate string `json:"effective_from_date"`
	IanaTz            string `json:"iana_tz"`
}

func (q *Queries) UpsertTzSegment(ctx context.Context, arg UpsertTzSegmentParams) (TzSegment, error) {
	row := q.db.QueryRowContext(ctx, upsertTzSegment, arg.PeriodID, arg.EffectiveFromDate, arg.IanaTz)
	var i TzSegment
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.EffectiveFromDate,
		&i.IanaTz,
	)
	return i, err
}
