// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package sqlc

import (
	"context"
	"database/sql"
)

const archiveProject = `-- name: ArchiveProject :one
UPDATE project
SET archived_at = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
RETURNING id, name, "key", color, archived_at, created_at, updated_at
`

type ArchiveProjectParams struct {
	ArchivedAt sql.NullString `json:"archived_at"`
	ID         int64          `json:"id"`
}

func (q *Queries) ArchiveProject(ctx context.Context, arg ArchiveProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, archiveProject, arg.ArchivedAt, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Key,
		&i.Color,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countTimeEntryReferencesToProject = `-- name: CountTimeEntryReferencesToProject :one
SELECT COUNT(*) FROM time_entry WHERE project_id = ?
`

func (q *Queries) CountTimeEntryReferencesToProject(ctx context.Context, projectID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTimeEntryReferencesToProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO project (name, key, color)
VALUES (?, ?, ?)
RETURNING id, name, "key", color, archived_at, created_at, updated_at
`

type CreateProjectParams struct {
	Name  string         `json:"name"`
	Key   string         `json:"key"`
	Color sql.NullString `json:"color"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Name, arg.Key, arg.Color)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Key,
		&i.Color,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM project WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, "key", color, archived_at, created_at, updated_at FROM project WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Key,
		&i.Color,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByKey = `-- name: GetProjectByKey :one
SELECT id, name, "key", color, archived_at, created_at, updated_at FROM project WHERE key = ? AND archived_at IS NULL
`

func (q *Queries) GetProjectByKey(ctx context.Context, key string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByKey, key)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Key,
		&i.Color,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllProjects = `-- name: ListAllProjects :many
SELECT id, name, "key", color, archived_at, created_at, updated_at FROM project ORDER BY name
`

func (q *Queries) ListAllProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Key,
			&i.Color,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, "key", color, archived_at, created_at, updated_at FROM project WHERE archived_at IS NULL ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Key,
			&i.Color,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE project
SET name = ?, key = ?, color = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
RETURNING id, name, "key", color, archived_at, created_at, updated_at
`

type UpdateProjectParams struct {
	Name  string         `json:"name"`
	Key   string         `json:"key"`
	Color sql.NullString `json:"color"`
	ID    int64          `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.Name,
		arg.Key,
		arg.Color,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Key,
		&i.Color,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
