// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	ArchiveCategory(ctx context.Context, arg ArchiveCategoryParams) (Category, error)
	ArchiveProject(ctx context.Context, arg ArchiveProjectParams) (Project, error)
	ClearDefaultGap(ctx context.Context) error
	CountCalendarReferencesToCategory(ctx context.Context, defaultCategoryID sql.NullInt64) (int64, error)
	CountMemoryReferencesToCategory(ctx context.Context, categoryID int64) (int64, error)
	CountOverlayReferencesToCategory(ctx context.Context, categoryID sql.NullInt64) (int64, error)
	CountTimeEntryReferencesToCategory(ctx context.Context, categoryID sql.NullInt64) (int64, error)
	CountTimeEntryReferencesToProject(ctx context.Context, projectID sql.NullInt64) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateExportTemplate(ctx context.Context, arg CreateExportTemplateParams) (ExportTemplate, error)
	CreatePeriod(ctx context.Context, arg CreatePeriodParams) (Period, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateReviewItem(ctx context.Context, arg CreateReviewItemParams) (ReviewItem, error)
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	CreateTimeEntry(ctx context.Context, arg CreateTimeEntryParams) (TimeEntry, error)
	DeleteBitbucketReposByAccount(ctx context.Context, accountID string) error
	DeleteBitbucketWorkspacesByAccount(ctx context.Context, accountID string) error
	DeleteCategory(ctx context.Context, id int64) error
	DeleteEvent(ctx context.Context, id int64) error
	DeleteExportTemplate(ctx context.Context, id int64) (int64, error)
	DeleteGitHubReposByAccount(ctx context.Context, accountID string) error
	DeleteIntegrationConnection(ctx context.Context, arg DeleteIntegrationConnectionParams) error
	DeleteOverlay(ctx context.Context, id int64) error
	DeletePeriod(ctx context.Context, id int64) error
	DeleteProject(ctx context.Context, id int64) error
	DeleteSlackChannelsByAccount(ctx context.Context, accountID string) error
	DeleteTimeEntry(ctx context.Context, arg DeleteTimeEntryParams) (int64, error)
	DeleteTzSegment(ctx context.Context, id int64) error
	ExportTemplateKeyExists(ctx context.Context, key string) (int64, error)
	ForgetMemory(ctx context.Context, matchKey string) error
	GetCalendar(ctx context.Context, id int64) (Calendar, error)
	GetCalendarByProviderExternalID(ctx context.Context, arg GetCalendarByProviderExternalIDParams) (Calendar, error)
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetCategoryByKey(ctx context.Context, key string) (Category, error)
	GetDefaultGapCategory(ctx context.Context) (Category, error)
	GetEvent(ctx context.Context, id int64) (Event, error)
	GetExportTemplate(ctx context.Context, id int64) (ExportTemplate, error)
	GetExportTemplateByKey(ctx context.Context, key string) (ExportTemplate, error)
	GetGitHubRepo(ctx context.Context, id int64) (GithubRepo, error)
	GetIntegrationConnection(ctx context.Context, arg GetIntegrationConnectionParams) (IntegrationConnection, error)
	GetLatestSubmission(ctx context.Context, periodID int64) (Submission, error)
	GetMemory(ctx context.Context, matchKey string) (Memory, error)
	GetOverlay(ctx context.Context, arg GetOverlayParams) (Overlay, error)
	GetPeriod(ctx context.Context, id int64) (Period, error)
	GetPeriodByRange(ctx context.Context, arg GetPeriodByRangeParams) (Period, error)
	GetProject(ctx context.Context, id int64) (Project, error)
	GetProjectByKey(ctx context.Context, key string) (Project, error)
	GetReviewItem(ctx context.Context, id int64) (ReviewItem, error)
	GetReviewItemByConflictKey(ctx context.Context, arg GetReviewItemByConflictKeyParams) (ReviewItem, error)
	GetSetting(ctx context.Context, key string) (string, error)
	GetSlackChannel(ctx context.Context, id int64) (SlackChannel, error)
	GetTimeEntry(ctx context.Context, arg GetTimeEntryParams) (TimeEntry, error)
	ListAllCategories(ctx context.Context) ([]Category, error)
	ListAllEventsForPeriod(ctx context.Context, periodID int64) ([]Event, error)
	ListAllProjects(ctx context.Context) ([]Project, error)
	ListBitbucketRepos(ctx context.Context) ([]BitbucketRepo, error)
	ListBitbucketReposByAccount(ctx context.Context, accountID string) ([]BitbucketRepo, error)
	ListBitbucketWorkspaces(ctx context.Context) ([]BitbucketWorkspace, error)
	ListBitbucketWorkspacesByAccount(ctx context.Context, accountID string) ([]BitbucketWorkspace, error)
	ListCalendars(ctx context.Context) ([]Calendar, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListEventsByIcalUID(ctx context.Context, arg ListEventsByIcalUIDParams) ([]Event, error)
	ListEventsForPeriod(ctx context.Context, periodID int64) ([]Event, error)
	ListExportTemplates(ctx context.Context) ([]ExportTemplate, error)
	ListGitHubRepos(ctx context.Context) ([]GithubRepo, error)
	ListGitHubReposByAccount(ctx context.Context, accountID string) ([]GithubRepo, error)
	ListIntegrationConnections(ctx context.Context) ([]IntegrationConnection, error)
	ListIntegrationConnectionsByProvider(ctx context.Context, provider string) ([]IntegrationConnection, error)
	ListMemory(ctx context.Context) ([]Memory, error)
	ListOpenReviewItems(ctx context.Context, periodID int64) ([]ReviewItem, error)
	ListOverlaysForPeriod(ctx context.Context, periodID int64) ([]Overlay, error)
	ListPeriods(ctx context.Context) ([]Period, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListSelectedBitbucketRepos(ctx context.Context) ([]BitbucketRepo, error)
	ListSelectedCalendars(ctx context.Context) ([]Calendar, error)
	ListSelectedGitHubRepos(ctx context.Context) ([]GithubRepo, error)
	ListSelectedSlackChannels(ctx context.Context) ([]SlackChannel, error)
	ListSettings(ctx context.Context) ([]AppSetting, error)
	ListSlackChannels(ctx context.Context) ([]SlackChannel, error)
	ListSlackChannelsByAccount(ctx context.Context, accountID string) ([]SlackChannel, error)
	ListSubmissions(ctx context.Context, periodID int64) ([]Submission, error)
	ListTimeEntriesForDay(ctx context.Context, arg ListTimeEntriesForDayParams) ([]TimeEntry, error)
	ListTimeEntriesForPeriod(ctx context.Context, periodID int64) ([]TimeEntry, error)
	ListTzSegments(ctx context.Context, periodID int64) ([]TzSegment, error)
	NextSubmissionVersion(ctx context.Context, periodID int64) (int64, error)
	// Train memory from a user correction; bump hit count on repeat.
	RememberCategory(ctx context.Context, arg RememberCategoryParams) (Memory, error)
	ResolveReviewItem(ctx context.Context, arg ResolveReviewItemParams) error
	SetBitbucketRepoSelected(ctx context.Context, arg SetBitbucketRepoSelectedParams) error
	SetBitbucketWorkspaceSelected(ctx context.Context, arg SetBitbucketWorkspaceSelectedParams) error
	SetCalendarDefaultCategory(ctx context.Context, arg SetCalendarDefaultCategoryParams) error
	SetCalendarSelected(ctx context.Context, arg SetCalendarSelectedParams) error
	SetDefaultGap(ctx context.Context, id int64) error
	// Soft-hide / restore all events from a calendar when it is deselected / reselected.
	SetEventActiveByCalendar(ctx context.Context, arg SetEventActiveByCalendarParams) error
	SetGitHubRepoSelected(ctx context.Context, arg SetGitHubRepoSelectedParams) error
	SetSetting(ctx context.Context, arg SetSettingParams) error
	SetSlackChannelSelected(ctx context.Context, arg SetSlackChannelSelectedParams) error
	TouchPeriodSynced(ctx context.Context, arg TouchPeriodSyncedParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateExportTemplate(ctx context.Context, arg UpdateExportTemplateParams) (ExportTemplate, error)
	UpdateIntegrationConnectionStatus(ctx context.Context, arg UpdateIntegrationConnectionStatusParams) error
	UpdatePeriodTarget(ctx context.Context, arg UpdatePeriodTargetParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateTimeEntry(ctx context.Context, arg UpdateTimeEntryParams) (TimeEntry, error)
	UpdateTimeEntrySpan(ctx context.Context, arg UpdateTimeEntrySpanParams) (TimeEntry, error)
	UpsertBitbucketRepo(ctx context.Context, arg UpsertBitbucketRepoParams) (BitbucketRepo, error)
	UpsertBitbucketWorkspace(ctx context.Context, arg UpsertBitbucketWorkspaceParams) (BitbucketWorkspace, error)
	UpsertCalendar(ctx context.Context, arg UpsertCalendarParams) (Calendar, error)
	// Re-sync entry point: insert a fact, or update mutable synced fields on re-pull.
	// Never touches user decisions (those live in overlay), and preserves `active`.
	UpsertEvent(ctx context.Context, arg UpsertEventParams) (Event, error)
	UpsertGitHubRepo(ctx context.Context, arg UpsertGitHubRepoParams) (GithubRepo, error)
	UpsertIntegrationConnection(ctx context.Context, arg UpsertIntegrationConnectionParams) (IntegrationConnection, error)
	UpsertOverlay(ctx context.Context, arg UpsertOverlayParams) (Overlay, error)
	UpsertSlackChannel(ctx context.Context, arg UpsertSlackChannelParams) (SlackChannel, error)
	UpsertTzSegment(ctx context.Context, arg UpsertTzSegmentParams) (TzSegment, error)
}

var _ Querier = (*Queries)(nil)
