// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	ClearDefaultGap(ctx context.Context) error
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateGapFill(ctx context.Context, arg CreateGapFillParams) (GapFill, error)
	CreatePeriod(ctx context.Context, arg CreatePeriodParams) (Period, error)
	CreateReviewItem(ctx context.Context, arg CreateReviewItemParams) (ReviewItem, error)
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	DeleteCategory(ctx context.Context, id int64) error
	DeleteEvent(ctx context.Context, id int64) error
	DeleteIntegrationConnection(ctx context.Context, arg DeleteIntegrationConnectionParams) error
	DeleteManualGapFill(ctx context.Context, arg DeleteManualGapFillParams) (int64, error)
	DeleteOverlay(ctx context.Context, id int64) error
	DeletePeriod(ctx context.Context, id int64) error
	DeleteTzSegment(ctx context.Context, id int64) error
	ForgetMemory(ctx context.Context, matchKey string) error
	GetCalendarByProviderExternalID(ctx context.Context, arg GetCalendarByProviderExternalIDParams) (Calendar, error)
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetDefaultGapCategory(ctx context.Context) (Category, error)
	GetEvent(ctx context.Context, id int64) (Event, error)
	GetIntegrationConnection(ctx context.Context, arg GetIntegrationConnectionParams) (IntegrationConnection, error)
	GetLatestSubmission(ctx context.Context, periodID int64) (Submission, error)
	GetMemory(ctx context.Context, matchKey string) (Memory, error)
	GetOverlay(ctx context.Context, arg GetOverlayParams) (Overlay, error)
	GetPeriod(ctx context.Context, id int64) (Period, error)
	GetPeriodByRange(ctx context.Context, arg GetPeriodByRangeParams) (Period, error)
	GetSetting(ctx context.Context, key string) (string, error)
	ListAllEventsForPeriod(ctx context.Context, periodID int64) ([]Event, error)
	ListCalendars(ctx context.Context) ([]Calendar, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListEventsByIcalUID(ctx context.Context, arg ListEventsByIcalUIDParams) ([]Event, error)
	ListEventsForPeriod(ctx context.Context, periodID int64) ([]Event, error)
	ListGapFillsForDay(ctx context.Context, arg ListGapFillsForDayParams) ([]GapFill, error)
	ListGapFillsForPeriod(ctx context.Context, periodID int64) ([]GapFill, error)
	ListIntegrationConnections(ctx context.Context) ([]IntegrationConnection, error)
	ListIntegrationConnectionsByProvider(ctx context.Context, provider string) ([]IntegrationConnection, error)
	ListMemory(ctx context.Context) ([]Memory, error)
	ListOpenReviewItems(ctx context.Context, periodID int64) ([]ReviewItem, error)
	ListOverlaysForPeriod(ctx context.Context, periodID int64) ([]Overlay, error)
	ListPeriods(ctx context.Context) ([]Period, error)
	ListSelectedCalendars(ctx context.Context) ([]Calendar, error)
	ListSettings(ctx context.Context) ([]AppSetting, error)
	ListSubmissions(ctx context.Context, periodID int64) ([]Submission, error)
	ListTzSegments(ctx context.Context, periodID int64) ([]TzSegment, error)
	NextSubmissionVersion(ctx context.Context, periodID int64) (int64, error)
	// Train memory from a user correction; bump hit count on repeat.
	RememberCategory(ctx context.Context, arg RememberCategoryParams) (Memory, error)
	RenameCategory(ctx context.Context, arg RenameCategoryParams) error
	ResolveReviewItem(ctx context.Context, arg ResolveReviewItemParams) error
	SetCalendarDefaultCategory(ctx context.Context, arg SetCalendarDefaultCategoryParams) error
	SetCalendarSelected(ctx context.Context, arg SetCalendarSelectedParams) error
	SetDefaultGap(ctx context.Context, id int64) error
	// Soft-hide / restore all events from a calendar when it is deselected / reselected.
	SetEventActiveByCalendar(ctx context.Context, arg SetEventActiveByCalendarParams) error
	SetSetting(ctx context.Context, arg SetSettingParams) error
	TouchPeriodSynced(ctx context.Context, arg TouchPeriodSyncedParams) error
	UpdateGapFill(ctx context.Context, arg UpdateGapFillParams) (GapFill, error)
	UpdateIntegrationConnectionStatus(ctx context.Context, arg UpdateIntegrationConnectionStatusParams) error
	UpdatePeriodTarget(ctx context.Context, arg UpdatePeriodTargetParams) error
	UpsertCalendar(ctx context.Context, arg UpsertCalendarParams) (Calendar, error)
	// Re-sync entry point: insert a fact, or update mutable synced fields on re-pull.
	// Never touches user decisions (those live in overlay), and preserves `active`.
	UpsertEvent(ctx context.Context, arg UpsertEventParams) (Event, error)
	UpsertIntegrationConnection(ctx context.Context, arg UpsertIntegrationConnectionParams) (IntegrationConnection, error)
	UpsertOverlay(ctx context.Context, arg UpsertOverlayParams) (Overlay, error)
	UpsertTzSegment(ctx context.Context, arg UpsertTzSegmentParams) (TzSegment, error)
}

var _ Querier = (*Queries)(nil)
