// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review_item.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createReviewItem = `-- name: CreateReviewItem :one
INSERT INTO review_item (period_id, kind, event_id, payload, conflict_key)
VALUES (?, ?, ?, ?, ?)
RETURNING id, period_id, kind, event_id, payload, status, created_at, resolved_at, conflict_key, decision_action, decision_payload
`

type CreateReviewItemParams struct {
	PeriodID    int64         `json:"period_id"`
	Kind        string        `json:"kind"`
	EventID     sql.NullInt64 `json:"event_id"`
	Payload     string        `json:"payload"`
	ConflictKey string        `json:"conflict_key"`
}

func (q *Queries) CreateReviewItem(ctx context.Context, arg CreateReviewItemParams) (ReviewItem, error) {
	row := q.db.QueryRowContext(ctx, createReviewItem,
		arg.PeriodID,
		arg.Kind,
		arg.EventID,
		arg.Payload,
		arg.ConflictKey,
	)
	var i ReviewItem
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.Kind,
		&i.EventID,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ConflictKey,
		&i.DecisionAction,
		&i.DecisionPayload,
	)
	return i, err
}

const getReviewItem = `-- name: GetReviewItem :one
SELECT id, period_id, kind, event_id, payload, status, created_at, resolved_at, conflict_key, decision_action, decision_payload FROM review_item WHERE id = ?
`

func (q *Queries) GetReviewItem(ctx context.Context, id int64) (ReviewItem, error) {
	row := q.db.QueryRowContext(ctx, getReviewItem, id)
	var i ReviewItem
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.Kind,
		&i.EventID,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ConflictKey,
		&i.DecisionAction,
		&i.DecisionPayload,
	)
	return i, err
}

const getReviewItemByConflictKey = `-- name: GetReviewItemByConflictKey :one
SELECT id, period_id, kind, event_id, payload, status, created_at, resolved_at, conflict_key, decision_action, decision_payload FROM review_item
WHERE period_id = ? AND kind = ? AND conflict_key = ?
ORDER BY CASE status WHEN 'open' THEN 0 ELSE 1 END, created_at DESC
LIMIT 1
`

type GetReviewItemByConflictKeyParams struct {
	PeriodID    int64  `json:"period_id"`
	Kind        string `json:"kind"`
	ConflictKey string `json:"conflict_key"`
}

func (q *Queries) GetReviewItemByConflictKey(ctx context.Context, arg GetReviewItemByConflictKeyParams) (ReviewItem, error) {
	row := q.db.QueryRowContext(ctx, getReviewItemByConflictKey, arg.PeriodID, arg.Kind, arg.ConflictKey)
	var i ReviewItem
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.Kind,
		&i.EventID,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ConflictKey,
		&i.DecisionAction,
		&i.DecisionPayload,
	)
	return i, err
}

const listOpenReviewItems = `-- name: ListOpenReviewItems :many
SELECT id, period_id, kind, event_id, payload, status, created_at, resolved_at, conflict_key, decision_action, decision_payload FROM review_item WHERE period_id = ? AND status = 'open' ORDER BY created_at
`

func (q *Queries) ListOpenReviewItems(ctx context.Context, periodID int64) ([]ReviewItem, error) {
	rows, err := q.db.QueryContext(ctx, listOpenReviewItems, periodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewItem{}
	for rows.Next() {
		var i ReviewItem
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.Kind,
			&i.EventID,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.ConflictKey,
			&i.DecisionAction,
			&i.DecisionPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveReviewItem = `-- name: ResolveReviewItem :exec
UPDATE review_item
SET status = ?,
    decision_action = ?,
    decision_payload = ?,
    resolved_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type ResolveReviewItemParams struct {
	Status          string `json:"status"`
	DecisionAction  string `json:"decision_action"`
	DecisionPayload string `json:"decision_payload"`
	ID              int64  `json:"id"`
}

func (q *Queries) ResolveReviewItem(ctx context.Context, arg ResolveReviewItemParams) error {
	_, err := q.db.ExecContext(ctx, resolveReviewItem,
		arg.Status,
		arg.DecisionAction,
		arg.DecisionPayload,
		arg.ID,
	)
	return err
}
