// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submission.sql

package sqlc

import (
	"context"
)

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submission (period_id, version, frozen_blob)
VALUES (?, ?, ?)
RETURNING id, period_id, version, finalized_at, frozen_blob
`

type CreateSubmissionParams struct {
	PeriodID   int64  `json:"period_id"`
	Version    int64  `json:"version"`
	FrozenBlob string `json:"frozen_blob"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRowContext(ctx, createSubmission, arg.PeriodID, arg.Version, arg.FrozenBlob)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.Version,
		&i.FinalizedAt,
		&i.FrozenBlob,
	)
	return i, err
}

const getLatestSubmission = `-- name: GetLatestSubmission :one
SELECT id, period_id, version, finalized_at, frozen_blob FROM submission WHERE period_id = ? ORDER BY version DESC LIMIT 1
`

func (q *Queries) GetLatestSubmission(ctx context.Context, periodID int64) (Submission, error) {
	row := q.db.QueryRowContext(ctx, getLatestSubmission, periodID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.Version,
		&i.FinalizedAt,
		&i.FrozenBlob,
	)
	return i, err
}

const listSubmissions = `-- name: ListSubmissions :many
SELECT id, period_id, version, finalized_at, frozen_blob FROM submission WHERE period_id = ? ORDER BY version DESC
`

func (q *Queries) ListSubmissions(ctx context.Context, periodID int64) ([]Submission, error) {
	rows, err := q.db.QueryContext(ctx, listSubmissions, periodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.Version,
			&i.FinalizedAt,
			&i.FrozenBlob,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSubmissionVersion = `-- name: NextSubmissionVersion :one
SELECT COALESCE(MAX(version), 0) + 1 AS next_version FROM submission WHERE period_id = ?
`

func (q *Queries) NextSubmissionVersion(ctx context.Context, periodID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextSubmissionVersion, periodID)
	var next_version int64
	err := row.Scan(&next_version)
	return next_version, err
}
