// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: time_entry.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTimeEntry = `-- name: CreateTimeEntry :one
INSERT INTO time_entry (
    period_id,
    start_instant,
    end_instant,
    duration_minutes,
    local_work_date,
    category_id,
    description,
    attestation,
    source_kind,
    source_id,
    source_revision,
    method
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, period_id, start_instant, end_instant, duration_minutes, local_work_date, category_id, description, attestation, source_kind, source_id, source_revision, method, created_at, updated_at, work_type, project_id, billable_status
`

type CreateTimeEntryParams struct {
	PeriodID        int64          `json:"period_id"`
	StartInstant    string         `json:"start_instant"`
	EndInstant      string         `json:"end_instant"`
	DurationMinutes int64          `json:"duration_minutes"`
	LocalWorkDate   string         `json:"local_work_date"`
	CategoryID      sql.NullInt64  `json:"category_id"`
	Description     string         `json:"description"`
	Attestation     string         `json:"attestation"`
	SourceKind      sql.NullString `json:"source_kind"`
	SourceID        sql.NullString `json:"source_id"`
	SourceRevision  sql.NullString `json:"source_revision"`
	Method          sql.NullString `json:"method"`
}

func (q *Queries) CreateTimeEntry(ctx context.Context, arg CreateTimeEntryParams) (TimeEntry, error) {
	row := q.db.QueryRowContext(ctx, createTimeEntry,
		arg.PeriodID,
		arg.StartInstant,
		arg.EndInstant,
		arg.DurationMinutes,
		arg.LocalWorkDate,
		arg.CategoryID,
		arg.Description,
		arg.Attestation,
		arg.SourceKind,
		arg.SourceID,
		arg.SourceRevision,
		arg.Method,
	)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.StartInstant,
		&i.EndInstant,
		&i.DurationMinutes,
		&i.LocalWorkDate,
		&i.CategoryID,
		&i.Description,
		&i.Attestation,
		&i.SourceKind,
		&i.SourceID,
		&i.SourceRevision,
		&i.Method,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkType,
		&i.ProjectID,
		&i.BillableStatus,
	)
	return i, err
}

const deleteTimeEntry = `-- name: DeleteTimeEntry :execrows
DELETE FROM time_entry WHERE id = ? AND period_id = ?
`

type DeleteTimeEntryParams struct {
	ID       int64 `json:"id"`
	PeriodID int64 `json:"period_id"`
}

func (q *Queries) DeleteTimeEntry(ctx context.Context, arg DeleteTimeEntryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTimeEntry, arg.ID, arg.PeriodID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTimeEntry = `-- name: GetTimeEntry :one
SELECT id, period_id, start_instant, end_instant, duration_minutes, local_work_date, category_id, description, attestation, source_kind, source_id, source_revision, method, created_at, updated_at, work_type, project_id, billable_status FROM time_entry WHERE id = ? AND period_id = ?
`

type GetTimeEntryParams struct {
	ID       int64 `json:"id"`
	PeriodID int64 `json:"period_id"`
}

func (q *Queries) GetTimeEntry(ctx context.Context, arg GetTimeEntryParams) (TimeEntry, error) {
	row := q.db.QueryRowContext(ctx, getTimeEntry, arg.ID, arg.PeriodID)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.StartInstant,
		&i.EndInstant,
		&i.DurationMinutes,
		&i.LocalWorkDate,
		&i.CategoryID,
		&i.Description,
		&i.Attestation,
		&i.SourceKind,
		&i.SourceID,
		&i.SourceRevision,
		&i.Method,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkType,
		&i.ProjectID,
		&i.BillableStatus,
	)
	return i, err
}

const listTimeEntriesForDay = `-- name: ListTimeEntriesForDay :many
SELECT id, period_id, start_instant, end_instant, duration_minutes, local_work_date, category_id, description, attestation, source_kind, source_id, source_revision, method, created_at, updated_at, work_type, project_id, billable_status FROM time_entry WHERE period_id = ? AND local_work_date = ? ORDER BY start_instant
`

type ListTimeEntriesForDayParams struct {
	PeriodID      int64  `json:"period_id"`
	LocalWorkDate string `json:"local_work_date"`
}

func (q *Queries) ListTimeEntriesForDay(ctx context.Context, arg ListTimeEntriesForDayParams) ([]TimeEntry, error) {
	rows, err := q.db.QueryContext(ctx, listTimeEntriesForDay, arg.PeriodID, arg.LocalWorkDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimeEntry{}
	for rows.Next() {
		var i TimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.StartInstant,
			&i.EndInstant,
			&i.DurationMinutes,
			&i.LocalWorkDate,
			&i.CategoryID,
			&i.Description,
			&i.Attestation,
			&i.SourceKind,
			&i.SourceID,
			&i.SourceRevision,
			&i.Method,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkType,
			&i.ProjectID,
			&i.BillableStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeEntriesForPeriod = `-- name: ListTimeEntriesForPeriod :many
SELECT id, period_id, start_instant, end_instant, duration_minutes, local_work_date, category_id, description, attestation, source_kind, source_id, source_revision, method, created_at, updated_at, work_type, project_id, billable_status FROM time_entry WHERE period_id = ? ORDER BY local_work_date, start_instant
`

func (q *Queries) ListTimeEntriesForPeriod(ctx context.Context, periodID int64) ([]TimeEntry, error) {
	rows, err := q.db.QueryContext(ctx, listTimeEntriesForPeriod, periodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimeEntry{}
	for rows.Next() {
		var i TimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.StartInstant,
			&i.EndInstant,
			&i.DurationMinutes,
			&i.LocalWorkDate,
			&i.CategoryID,
			&i.Description,
			&i.Attestation,
			&i.SourceKind,
			&i.SourceID,
			&i.SourceRevision,
			&i.Method,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkType,
			&i.ProjectID,
			&i.BillableStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimeEntry = `-- name: UpdateTimeEntry :one
UPDATE time_entry SET
    start_instant     = ?,
    end_instant       = ?,
    duration_minutes  = ?,
    local_work_date   = ?,
    category_id       = ?,
    description       = ?,
    updated_at        = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND period_id = ?
RETURNING id, period_id, start_instant, end_instant, duration_minutes, local_work_date, category_id, description, attestation, source_kind, source_id, source_revision, method, created_at, updated_at, work_type, project_id, billable_status
`

type UpdateTimeEntryParams struct {
	StartInstant    string        `json:"start_instant"`
	EndInstant      string        `json:"end_instant"`
	DurationMinutes int64         `json:"duration_minutes"`
	LocalWorkDate   string        `json:"local_work_date"`
	CategoryID      sql.NullInt64 `json:"category_id"`
	Description     string        `json:"description"`
	ID              int64         `json:"id"`
	PeriodID        int64         `json:"period_id"`
}

func (q *Queries) UpdateTimeEntry(ctx context.Context, arg UpdateTimeEntryParams) (TimeEntry, error) {
	row := q.db.QueryRowContext(ctx, updateTimeEntry,
		arg.StartInstant,
		arg.EndInstant,
		arg.DurationMinutes,
		arg.LocalWorkDate,
		arg.CategoryID,
		arg.Description,
		arg.ID,
		arg.PeriodID,
	)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.StartInstant,
		&i.EndInstant,
		&i.DurationMinutes,
		&i.LocalWorkDate,
		&i.CategoryID,
		&i.Description,
		&i.Attestation,
		&i.SourceKind,
		&i.SourceID,
		&i.SourceRevision,
		&i.Method,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkType,
		&i.ProjectID,
		&i.BillableStatus,
	)
	return i, err
}

const updateTimeEntrySpan = `-- name: UpdateTimeEntrySpan :one
UPDATE time_entry SET
    start_instant     = ?,
    end_instant       = ?,
    duration_minutes  = ?,
    local_work_date   = ?,
    updated_at        = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND period_id = ?
RETURNING id, period_id, start_instant, end_instant, duration_minutes, local_work_date, category_id, description, attestation, source_kind, source_id, source_revision, method, created_at, updated_at, work_type, project_id, billable_status
`

type UpdateTimeEntrySpanParams struct {
	StartInstant    string `json:"start_instant"`
	EndInstant      string `json:"end_instant"`
	DurationMinutes int64  `json:"duration_minutes"`
	LocalWorkDate   string `json:"local_work_date"`
	ID              int64  `json:"id"`
	PeriodID        int64  `json:"period_id"`
}

func (q *Queries) UpdateTimeEntrySpan(ctx context.Context, arg UpdateTimeEntrySpanParams) (TimeEntry, error) {
	row := q.db.QueryRowContext(ctx, updateTimeEntrySpan,
		arg.StartInstant,
		arg.EndInstant,
		arg.DurationMinutes,
		arg.LocalWorkDate,
		arg.ID,
		arg.PeriodID,
	)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.StartInstant,
		&i.EndInstant,
		&i.DurationMinutes,
		&i.LocalWorkDate,
		&i.CategoryID,
		&i.Description,
		&i.Attestation,
		&i.SourceKind,
		&i.SourceID,
		&i.SourceRevision,
		&i.Method,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkType,
		&i.ProjectID,
		&i.BillableStatus,
	)
	return i, err
}
