// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_schedule.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countWorkSchedules = `-- name: CountWorkSchedules :one
SELECT COUNT(*) FROM work_schedule
`

func (q *Queries) CountWorkSchedules(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkSchedules)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScheduleException = `-- name: CreateScheduleException :one
INSERT INTO schedule_exception (date, kind, expected_minutes)
VALUES (?, ?, ?)
RETURNING id, date, kind, expected_minutes, created_at
`

type CreateScheduleExceptionParams struct {
	Date            string `json:"date"`
	Kind            string `json:"kind"`
	ExpectedMinutes int64  `json:"expected_minutes"`
}

func (q *Queries) CreateScheduleException(ctx context.Context, arg CreateScheduleExceptionParams) (ScheduleException, error) {
	row := q.db.QueryRowContext(ctx, createScheduleException, arg.Date, arg.Kind, arg.ExpectedMinutes)
	var i ScheduleException
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Kind,
		&i.ExpectedMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const createScheduleExceptionWindow = `-- name: CreateScheduleExceptionWindow :one
INSERT INTO schedule_exception_window (schedule_exception_id, start_minutes, end_minutes)
VALUES (?, ?, ?)
RETURNING id, schedule_exception_id, start_minutes, end_minutes
`

type CreateScheduleExceptionWindowParams struct {
	ScheduleExceptionID int64 `json:"schedule_exception_id"`
	StartMinutes        int64 `json:"start_minutes"`
	EndMinutes          int64 `json:"end_minutes"`
}

func (q *Queries) CreateScheduleExceptionWindow(ctx context.Context, arg CreateScheduleExceptionWindowParams) (ScheduleExceptionWindow, error) {
	row := q.db.QueryRowContext(ctx, createScheduleExceptionWindow, arg.ScheduleExceptionID, arg.StartMinutes, arg.EndMinutes)
	var i ScheduleExceptionWindow
	err := row.Scan(
		&i.ID,
		&i.ScheduleExceptionID,
		&i.StartMinutes,
		&i.EndMinutes,
	)
	return i, err
}

const createWorkSchedule = `-- name: CreateWorkSchedule :one
INSERT INTO work_schedule (timezone, workweek_start, effective_from, effective_to)
VALUES (?, ?, ?, ?)
RETURNING id, timezone, workweek_start, effective_from, effective_to, created_at
`

type CreateWorkScheduleParams struct {
	Timezone      string         `json:"timezone"`
	WorkweekStart string         `json:"workweek_start"`
	EffectiveFrom string         `json:"effective_from"`
	EffectiveTo   sql.NullString `json:"effective_to"`
}

func (q *Queries) CreateWorkSchedule(ctx context.Context, arg CreateWorkScheduleParams) (WorkSchedule, error) {
	row := q.db.QueryRowContext(ctx, createWorkSchedule,
		arg.Timezone,
		arg.WorkweekStart,
		arg.EffectiveFrom,
		arg.EffectiveTo,
	)
	var i WorkSchedule
	err := row.Scan(
		&i.ID,
		&i.Timezone,
		&i.WorkweekStart,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkScheduleDay = `-- name: CreateWorkScheduleDay :one
INSERT INTO work_schedule_day (work_schedule_id, weekday, expected_minutes)
VALUES (?, ?, ?)
RETURNING id, work_schedule_id, weekday, expected_minutes
`

type CreateWorkScheduleDayParams struct {
	WorkScheduleID  int64  `json:"work_schedule_id"`
	Weekday         string `json:"weekday"`
	ExpectedMinutes int64  `json:"expected_minutes"`
}

func (q *Queries) CreateWorkScheduleDay(ctx context.Context, arg CreateWorkScheduleDayParams) (WorkScheduleDay, error) {
	row := q.db.QueryRowContext(ctx, createWorkScheduleDay, arg.WorkScheduleID, arg.Weekday, arg.ExpectedMinutes)
	var i WorkScheduleDay
	err := row.Scan(
		&i.ID,
		&i.WorkScheduleID,
		&i.Weekday,
		&i.ExpectedMinutes,
	)
	return i, err
}

const createWorkScheduleWindow = `-- name: CreateWorkScheduleWindow :one
INSERT INTO work_schedule_window (work_schedule_day_id, start_minutes, end_minutes)
VALUES (?, ?, ?)
RETURNING id, work_schedule_day_id, start_minutes, end_minutes
`

type CreateWorkScheduleWindowParams struct {
	WorkScheduleDayID int64 `json:"work_schedule_day_id"`
	StartMinutes      int64 `json:"start_minutes"`
	EndMinutes        int64 `json:"end_minutes"`
}

func (q *Queries) CreateWorkScheduleWindow(ctx context.Context, arg CreateWorkScheduleWindowParams) (WorkScheduleWindow, error) {
	row := q.db.QueryRowContext(ctx, createWorkScheduleWindow, arg.WorkScheduleDayID, arg.StartMinutes, arg.EndMinutes)
	var i WorkScheduleWindow
	err := row.Scan(
		&i.ID,
		&i.WorkScheduleDayID,
		&i.StartMinutes,
		&i.EndMinutes,
	)
	return i, err
}

const deleteScheduleException = `-- name: DeleteScheduleException :exec
DELETE FROM schedule_exception WHERE id = ?
`

func (q *Queries) DeleteScheduleException(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteScheduleException, id)
	return err
}

const deleteScheduleExceptionWindows = `-- name: DeleteScheduleExceptionWindows :exec
DELETE FROM schedule_exception_window WHERE schedule_exception_id = ?
`

func (q *Queries) DeleteScheduleExceptionWindows(ctx context.Context, scheduleExceptionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteScheduleExceptionWindows, scheduleExceptionID)
	return err
}

const getScheduleExceptionByDate = `-- name: GetScheduleExceptionByDate :one
SELECT id, date, kind, expected_minutes, created_at FROM schedule_exception WHERE date = ?
`

func (q *Queries) GetScheduleExceptionByDate(ctx context.Context, date string) (ScheduleException, error) {
	row := q.db.QueryRowContext(ctx, getScheduleExceptionByDate, date)
	var i ScheduleException
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Kind,
		&i.ExpectedMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkSchedule = `-- name: GetWorkSchedule :one
SELECT id, timezone, workweek_start, effective_from, effective_to, created_at FROM work_schedule WHERE id = ?
`

func (q *Queries) GetWorkSchedule(ctx context.Context, id int64) (WorkSchedule, error) {
	row := q.db.QueryRowContext(ctx, getWorkSchedule, id)
	var i WorkSchedule
	err := row.Scan(
		&i.ID,
		&i.Timezone,
		&i.WorkweekStart,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkScheduleForDate = `-- name: GetWorkScheduleForDate :one
SELECT id, timezone, workweek_start, effective_from, effective_to, created_at FROM work_schedule
WHERE effective_from <= ?1
  AND (effective_to IS NULL OR effective_to > ?1)
LIMIT 1
`

func (q *Queries) GetWorkScheduleForDate(ctx context.Context, date string) (WorkSchedule, error) {
	row := q.db.QueryRowContext(ctx, getWorkScheduleForDate, date)
	var i WorkSchedule
	err := row.Scan(
		&i.ID,
		&i.Timezone,
		&i.WorkweekStart,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
	)
	return i, err
}

const listScheduleExceptionWindows = `-- name: ListScheduleExceptionWindows :many
SELECT id, schedule_exception_id, start_minutes, end_minutes FROM schedule_exception_window
WHERE schedule_exception_id = ?
ORDER BY start_minutes
`

func (q *Queries) ListScheduleExceptionWindows(ctx context.Context, scheduleExceptionID int64) ([]ScheduleExceptionWindow, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleExceptionWindows, scheduleExceptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleExceptionWindow{}
	for rows.Next() {
		var i ScheduleExceptionWindow
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleExceptionID,
			&i.StartMinutes,
			&i.EndMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleExceptions = `-- name: ListScheduleExceptions :many
SELECT id, date, kind, expected_minutes, created_at FROM schedule_exception ORDER BY date
`

func (q *Queries) ListScheduleExceptions(ctx context.Context) ([]ScheduleException, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleExceptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleException{}
	for rows.Next() {
		var i ScheduleException
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Kind,
			&i.ExpectedMinutes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkScheduleDays = `-- name: ListWorkScheduleDays :many
SELECT id, work_schedule_id, weekday, expected_minutes FROM work_schedule_day
WHERE work_schedule_id = ?
ORDER BY CASE weekday
    WHEN 'monday' THEN 1 WHEN 'tuesday' THEN 2 WHEN 'wednesday' THEN 3
    WHEN 'thursday' THEN 4 WHEN 'friday' THEN 5 WHEN 'saturday' THEN 6
    WHEN 'sunday' THEN 7 END
`

func (q *Queries) ListWorkScheduleDays(ctx context.Context, workScheduleID int64) ([]WorkScheduleDay, error) {
	rows, err := q.db.QueryContext(ctx, listWorkScheduleDays, workScheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkScheduleDay{}
	for rows.Next() {
		var i WorkScheduleDay
		if err := rows.Scan(
			&i.ID,
			&i.WorkScheduleID,
			&i.Weekday,
			&i.ExpectedMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkScheduleWindows = `-- name: ListWorkScheduleWindows :many
SELECT id, work_schedule_day_id, start_minutes, end_minutes FROM work_schedule_window
WHERE work_schedule_day_id = ?
ORDER BY start_minutes
`

func (q *Queries) ListWorkScheduleWindows(ctx context.Context, workScheduleDayID int64) ([]WorkScheduleWindow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkScheduleWindows, workScheduleDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkScheduleWindow{}
	for rows.Next() {
		var i WorkScheduleWindow
		if err := rows.Scan(
			&i.ID,
			&i.WorkScheduleDayID,
			&i.StartMinutes,
			&i.EndMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkSchedules = `-- name: ListWorkSchedules :many
SELECT id, timezone, workweek_start, effective_from, effective_to, created_at FROM work_schedule
ORDER BY effective_from
`

func (q *Queries) ListWorkSchedules(ctx context.Context) ([]WorkSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listWorkSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkSchedule{}
	for rows.Next() {
		var i WorkSchedule
		if err := rows.Scan(
			&i.ID,
			&i.Timezone,
			&i.WorkweekStart,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduleException = `-- name: UpdateScheduleException :one
UPDATE schedule_exception
SET kind = ?, expected_minutes = ?
WHERE id = ?
RETURNING id, date, kind, expected_minutes, created_at
`

type UpdateScheduleExceptionParams struct {
	Kind            string `json:"kind"`
	ExpectedMinutes int64  `json:"expected_minutes"`
	ID              int64  `json:"id"`
}

func (q *Queries) UpdateScheduleException(ctx context.Context, arg UpdateScheduleExceptionParams) (ScheduleException, error) {
	row := q.db.QueryRowContext(ctx, updateScheduleException, arg.Kind, arg.ExpectedMinutes, arg.ID)
	var i ScheduleException
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Kind,
		&i.ExpectedMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const updateWorkScheduleEffectiveTo = `-- name: UpdateWorkScheduleEffectiveTo :one
UPDATE work_schedule
SET effective_to = ?
WHERE id = ?
RETURNING id, timezone, workweek_start, effective_from, effective_to, created_at
`

type UpdateWorkScheduleEffectiveToParams struct {
	EffectiveTo sql.NullString `json:"effective_to"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateWorkScheduleEffectiveTo(ctx context.Context, arg UpdateWorkScheduleEffectiveToParams) (WorkSchedule, error) {
	row := q.db.QueryRowContext(ctx, updateWorkScheduleEffectiveTo, arg.EffectiveTo, arg.ID)
	var i WorkSchedule
	err := row.Scan(
		&i.ID,
		&i.Timezone,
		&i.WorkweekStart,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
	)
	return i, err
}
