// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCategory(arg1, arg2) {
  return window['go']['service']['Service']['GetCategory'](arg1, arg2);
}

export function GetEvent(arg1, arg2) {
  return window['go']['service']['Service']['GetEvent'](arg1, arg2);
}

export function GetPeriod(arg1, arg2) {
  return window['go']['service']['Service']['GetPeriod'](arg1, arg2);
}

export function GetPeriodByRange(arg1, arg2, arg3) {
  return window['go']['service']['Service']['GetPeriodByRange'](arg1, arg2, arg3);
}

export function GetSetting(arg1, arg2) {
  return window['go']['service']['Service']['GetSetting'](arg1, arg2);
}

export function ListCalendars(arg1) {
  return window['go']['service']['Service']['ListCalendars'](arg1);
}

export function ListCategories(arg1) {
  return window['go']['service']['Service']['ListCategories'](arg1);
}

export function ListEvents(arg1, arg2) {
  return window['go']['service']['Service']['ListEvents'](arg1, arg2);
}

export function ListGapFills(arg1, arg2) {
  return window['go']['service']['Service']['ListGapFills'](arg1, arg2);
}

export function ListOpenReviewItems(arg1, arg2) {
  return window['go']['service']['Service']['ListOpenReviewItems'](arg1, arg2);
}

export function ListPeriods(arg1) {
  return window['go']['service']['Service']['ListPeriods'](arg1);
}

export function ListSelectedCalendars(arg1) {
  return window['go']['service']['Service']['ListSelectedCalendars'](arg1);
}

export function ListTzSegments(arg1, arg2) {
  return window['go']['service']['Service']['ListTzSegments'](arg1, arg2);
}

export function SyncEvents(arg1, arg2, arg3) {
  return window['go']['service']['Service']['SyncEvents'](arg1, arg2, arg3);
}
