// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {service} from '../models';
import {ai} from '../models';

export function ClassifyAIEndpoint(arg1:string):Promise<boolean|string>;

export function ComputeGaps(arg1:context.Context,arg2:number):Promise<Array<service.DayTimeline>>;

export function CreateCategory(arg1:context.Context,arg2:service.CreateCategoryInput):Promise<service.Category>;

export function CreateGapFill(arg1:context.Context,arg2:service.ManualEventInput):Promise<service.GapFill>;

export function CreateManualEvent(arg1:context.Context,arg2:service.ManualEventInput):Promise<service.GapFill>;

export function DeleteCategory(arg1:context.Context,arg2:number):Promise<void>;

export function DeleteManualEvent(arg1:context.Context,arg2:service.ManualEventDeleteInput):Promise<void>;

export function DiscoverLocalAIEndpoints(arg1:context.Context):Promise<Array<ai.Endpoint>>;

export function EnsureCurrentPeriod(arg1:context.Context,arg2:string,arg3:string):Promise<service.Period>;

export function GetCategory(arg1:context.Context,arg2:number):Promise<service.Category>;

export function GetEvent(arg1:context.Context,arg2:number):Promise<service.Event>;

export function GetPeriod(arg1:context.Context,arg2:number):Promise<service.Period>;

export function GetPeriodByRange(arg1:context.Context,arg2:string,arg3:string):Promise<service.Period>;

export function GetSetting(arg1:context.Context,arg2:string):Promise<string>;

export function ListAIModels(arg1:context.Context,arg2:string,arg3:string):Promise<Array<string>>;

export function ListCalendars(arg1:context.Context):Promise<Array<service.Calendar>>;

export function ListCategories(arg1:context.Context):Promise<Array<service.Category>>;

export function ListEvents(arg1:context.Context,arg2:number):Promise<Array<service.Event>>;

export function ListGapFills(arg1:context.Context,arg2:number):Promise<Array<service.GapFill>>;

export function ListOpenReviewItems(arg1:context.Context,arg2:number):Promise<Array<service.ReviewItem>>;

export function ListPeriods(arg1:context.Context):Promise<Array<service.Period>>;

export function ListSelectedCalendars(arg1:context.Context):Promise<Array<service.Calendar>>;

export function ListTzSegments(arg1:context.Context,arg2:number):Promise<Array<service.TzSegment>>;

export function ResolveReviewItem(arg1:context.Context,arg2:service.ResolveReviewItemInput):Promise<service.ResolveReviewItemResult>;

export function SaveAIConfig(arg1:context.Context,arg2:string,arg3:string):Promise<void>;

export function SaveAIEndpoint(arg1:context.Context,arg2:string):Promise<void>;

export function SaveAIModel(arg1:context.Context,arg2:string):Promise<void>;

export function SetCalendarDefaultCategory(arg1:context.Context,arg2:number,arg3:any):Promise<void>;

export function SetCalendarSelected(arg1:context.Context,arg2:number,arg3:boolean):Promise<void>;

export function SetCalendarSync(arg1:service.CalendarSyncConfig):Promise<void>;

export function SetEvidence(arg1:service.EvidenceConfig):Promise<void>;

export function SetSetting(arg1:context.Context,arg2:string,arg3:string):Promise<void>;

export function SuggestGapFill(arg1:context.Context,arg2:service.TimeWindow):Promise<service.GapSuggestion>;

export function SyncEvents(arg1:context.Context,arg2:number,arg3:Array<service.IncomingEvent>):Promise<service.SyncResult>;

export function SyncPeriod(arg1:context.Context,arg2:number):Promise<service.SyncResult>;

export function UpdateCategory(arg1:context.Context,arg2:service.UpdateCategoryInput):Promise<service.Category>;

export function UpdateManualEvent(arg1:context.Context,arg2:service.ManualEventUpdateInput):Promise<service.GapFill>;

export function ValidateAIConfig(arg1:context.Context,arg2:string,arg3:string,arg4:string):Promise<ai.ValidationResult>;
