// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClassifyAIEndpoint(arg1) {
  return window['go']['service']['Service']['ClassifyAIEndpoint'](arg1);
}

export function ComputeGaps(arg1, arg2) {
  return window['go']['service']['Service']['ComputeGaps'](arg1, arg2);
}

export function CreateCategory(arg1, arg2) {
  return window['go']['service']['Service']['CreateCategory'](arg1, arg2);
}

export function CreateGapFill(arg1, arg2) {
  return window['go']['service']['Service']['CreateGapFill'](arg1, arg2);
}

export function CreateManualEvent(arg1, arg2) {
  return window['go']['service']['Service']['CreateManualEvent'](arg1, arg2);
}

export function DeleteCategory(arg1, arg2) {
  return window['go']['service']['Service']['DeleteCategory'](arg1, arg2);
}

export function DeleteManualEvent(arg1, arg2) {
  return window['go']['service']['Service']['DeleteManualEvent'](arg1, arg2);
}

export function DiscoverLocalAIEndpoints(arg1) {
  return window['go']['service']['Service']['DiscoverLocalAIEndpoints'](arg1);
}

export function EnsureCurrentPeriod(arg1, arg2, arg3) {
  return window['go']['service']['Service']['EnsureCurrentPeriod'](arg1, arg2, arg3);
}

export function GetCategory(arg1, arg2) {
  return window['go']['service']['Service']['GetCategory'](arg1, arg2);
}

export function GetEvent(arg1, arg2) {
  return window['go']['service']['Service']['GetEvent'](arg1, arg2);
}

export function GetPeriod(arg1, arg2) {
  return window['go']['service']['Service']['GetPeriod'](arg1, arg2);
}

export function GetPeriodByRange(arg1, arg2, arg3) {
  return window['go']['service']['Service']['GetPeriodByRange'](arg1, arg2, arg3);
}

export function GetSetting(arg1, arg2) {
  return window['go']['service']['Service']['GetSetting'](arg1, arg2);
}

export function ListAIModels(arg1, arg2, arg3) {
  return window['go']['service']['Service']['ListAIModels'](arg1, arg2, arg3);
}

export function ListCalendars(arg1) {
  return window['go']['service']['Service']['ListCalendars'](arg1);
}

export function ListCategories(arg1) {
  return window['go']['service']['Service']['ListCategories'](arg1);
}

export function ListEventCategoryOverlays(arg1, arg2) {
  return window['go']['service']['Service']['ListEventCategoryOverlays'](arg1, arg2);
}

export function ListEvents(arg1, arg2) {
  return window['go']['service']['Service']['ListEvents'](arg1, arg2);
}

export function ListGapFills(arg1, arg2) {
  return window['go']['service']['Service']['ListGapFills'](arg1, arg2);
}

export function ListOpenReviewItems(arg1, arg2) {
  return window['go']['service']['Service']['ListOpenReviewItems'](arg1, arg2);
}

export function ListPeriods(arg1) {
  return window['go']['service']['Service']['ListPeriods'](arg1);
}

export function ListSelectedCalendars(arg1) {
  return window['go']['service']['Service']['ListSelectedCalendars'](arg1);
}

export function ListTzSegments(arg1, arg2) {
  return window['go']['service']['Service']['ListTzSegments'](arg1, arg2);
}

export function ResolveReviewItem(arg1, arg2) {
  return window['go']['service']['Service']['ResolveReviewItem'](arg1, arg2);
}

export function SaveAIConfig(arg1, arg2, arg3) {
  return window['go']['service']['Service']['SaveAIConfig'](arg1, arg2, arg3);
}

export function SaveAIEndpoint(arg1, arg2) {
  return window['go']['service']['Service']['SaveAIEndpoint'](arg1, arg2);
}

export function SaveAIModel(arg1, arg2) {
  return window['go']['service']['Service']['SaveAIModel'](arg1, arg2);
}

export function SetCalendarDefaultCategory(arg1, arg2, arg3) {
  return window['go']['service']['Service']['SetCalendarDefaultCategory'](arg1, arg2, arg3);
}

export function SetCalendarSelected(arg1, arg2, arg3) {
  return window['go']['service']['Service']['SetCalendarSelected'](arg1, arg2, arg3);
}

export function SetCalendarSync(arg1) {
  return window['go']['service']['Service']['SetCalendarSync'](arg1);
}

export function SetEvidence(arg1) {
  return window['go']['service']['Service']['SetEvidence'](arg1);
}

export function SetSetting(arg1, arg2, arg3) {
  return window['go']['service']['Service']['SetSetting'](arg1, arg2, arg3);
}

export function SuggestGapFill(arg1, arg2) {
  return window['go']['service']['Service']['SuggestGapFill'](arg1, arg2);
}

export function SyncEvents(arg1, arg2, arg3) {
  return window['go']['service']['Service']['SyncEvents'](arg1, arg2, arg3);
}

export function SyncPeriod(arg1, arg2) {
  return window['go']['service']['Service']['SyncPeriod'](arg1, arg2);
}

export function UpdateCategory(arg1, arg2) {
  return window['go']['service']['Service']['UpdateCategory'](arg1, arg2);
}

export function UpdateManualEvent(arg1, arg2) {
  return window['go']['service']['Service']['UpdateManualEvent'](arg1, arg2);
}

export function ValidateAIConfig(arg1, arg2, arg3, arg4) {
  return window['go']['service']['Service']['ValidateAIConfig'](arg1, arg2, arg3, arg4);
}
