// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {service} from '../models';

export function GetCategory(arg1:context.Context,arg2:number):Promise<service.Category>;

export function GetEvent(arg1:context.Context,arg2:number):Promise<service.Event>;

export function GetPeriod(arg1:context.Context,arg2:number):Promise<service.Period>;

export function GetPeriodByRange(arg1:context.Context,arg2:string,arg3:string):Promise<service.Period>;

export function GetSetting(arg1:context.Context,arg2:string):Promise<string>;

export function ListCalendars(arg1:context.Context):Promise<Array<service.Calendar>>;

export function ListCategories(arg1:context.Context):Promise<Array<service.Category>>;

export function ListEvents(arg1:context.Context,arg2:number):Promise<Array<service.Event>>;

export function ListGapFills(arg1:context.Context,arg2:number):Promise<Array<service.GapFill>>;

export function ListOpenReviewItems(arg1:context.Context,arg2:number):Promise<Array<service.ReviewItem>>;

export function ListPeriods(arg1:context.Context):Promise<Array<service.Period>>;

export function ListSelectedCalendars(arg1:context.Context):Promise<Array<service.Calendar>>;

export function ListTzSegments(arg1:context.Context,arg2:number):Promise<Array<service.TzSegment>>;

export function SyncEvents(arg1:context.Context,arg2:number,arg3:Array<service.IncomingEvent>):Promise<service.SyncResult>;
