/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsProjectsRouteImport } from './routes/settings/projects'
import { Route as SettingsWorkScheduleRouteImport } from './routes/settings/work-schedule'
import { Route as SettingsPrivacyRouteImport } from './routes/settings/privacy'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings/integrations'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'
import { Route as SettingsExportRouteImport } from './routes/settings/export'
import { Route as SettingsCategoriesRouteImport } from './routes/settings/categories'
import { Route as SettingsAiRouteImport } from './routes/settings/ai'
import { Route as SettingsIntegrationsIndexRouteImport } from './routes/settings/integrations/index'
import { Route as SettingsIntegrationsProviderIdRouteImport } from './routes/settings/integrations/$providerId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProjectsRoute = SettingsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsWorkScheduleRoute = SettingsWorkScheduleRouteImport.update({
  id: '/work-schedule',
  path: '/work-schedule',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExportRoute = SettingsExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCategoriesRoute = SettingsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAiRoute = SettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsIndexRoute =
  SettingsIntegrationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsIntegrationsRoute,
  } as any)
const SettingsIntegrationsProviderIdRoute =
  SettingsIntegrationsProviderIdRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => SettingsIntegrationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/ai': typeof SettingsAiRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRouteWithChildren
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/work-schedule': typeof SettingsWorkScheduleRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/integrations/$providerId': typeof SettingsIntegrationsProviderIdRoute
  '/settings/integrations/': typeof SettingsIntegrationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/work-schedule': typeof SettingsWorkScheduleRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/integrations/$providerId': typeof SettingsIntegrationsProviderIdRoute
  '/settings/integrations': typeof SettingsIntegrationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/ai': typeof SettingsAiRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRouteWithChildren
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/work-schedule': typeof SettingsWorkScheduleRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/integrations/$providerId': typeof SettingsIntegrationsProviderIdRoute
  '/settings/integrations/': typeof SettingsIntegrationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/settings'
    | '/settings/ai'
    | '/settings/categories'
    | '/settings/export'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/privacy'
    | '/settings/projects'
    | '/settings/work-schedule'
    | '/settings/'
    | '/settings/integrations/$providerId'
    | '/settings/integrations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/settings/ai'
    | '/settings/categories'
    | '/settings/export'
    | '/settings/general'
    | '/settings/privacy'
    | '/settings/projects'
    | '/settings/work-schedule'
    | '/settings'
    | '/settings/integrations/$providerId'
    | '/settings/integrations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/settings'
    | '/settings/ai'
    | '/settings/categories'
    | '/settings/export'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/privacy'
    | '/settings/projects'
    | '/settings/work-schedule'
    | '/settings/'
    | '/settings/integrations/$providerId'
    | '/settings/integrations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/projects': {
      id: '/settings/projects'
      path: '/projects'
      fullPath: '/settings/projects'
      preLoaderRoute: typeof SettingsProjectsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/work-schedule': {
      id: '/settings/work-schedule'
      path: '/work-schedule'
      fullPath: '/settings/work-schedule'
      preLoaderRoute: typeof SettingsWorkScheduleRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/export': {
      id: '/settings/export'
      path: '/export'
      fullPath: '/settings/export'
      preLoaderRoute: typeof SettingsExportRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/categories': {
      id: '/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof SettingsCategoriesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/ai': {
      id: '/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof SettingsAiRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations/': {
      id: '/settings/integrations/'
      path: '/'
      fullPath: '/settings/integrations/'
      preLoaderRoute: typeof SettingsIntegrationsIndexRouteImport
      parentRoute: typeof SettingsIntegrationsRoute
    }
    '/settings/integrations/$providerId': {
      id: '/settings/integrations/$providerId'
      path: '/$providerId'
      fullPath: '/settings/integrations/$providerId'
      preLoaderRoute: typeof SettingsIntegrationsProviderIdRouteImport
      parentRoute: typeof SettingsIntegrationsRoute
    }
  }
}

interface SettingsIntegrationsRouteChildren {
  SettingsIntegrationsProviderIdRoute: typeof SettingsIntegrationsProviderIdRoute
  SettingsIntegrationsIndexRoute: typeof SettingsIntegrationsIndexRoute
}

const SettingsIntegrationsRouteChildren: SettingsIntegrationsRouteChildren = {
  SettingsIntegrationsProviderIdRoute: SettingsIntegrationsProviderIdRoute,
  SettingsIntegrationsIndexRoute: SettingsIntegrationsIndexRoute,
}

const SettingsIntegrationsRouteWithChildren =
  SettingsIntegrationsRoute._addFileChildren(SettingsIntegrationsRouteChildren)

interface SettingsRouteChildren {
  SettingsAiRoute: typeof SettingsAiRoute
  SettingsCategoriesRoute: typeof SettingsCategoriesRoute
  SettingsExportRoute: typeof SettingsExportRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRouteWithChildren
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsProjectsRoute: typeof SettingsProjectsRoute
  SettingsWorkScheduleRoute: typeof SettingsWorkScheduleRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAiRoute: SettingsAiRoute,
  SettingsCategoriesRoute: SettingsCategoriesRoute,
  SettingsExportRoute: SettingsExportRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRouteWithChildren,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsProjectsRoute: SettingsProjectsRoute,
  SettingsWorkScheduleRoute: SettingsWorkScheduleRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
