// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClassifyAIEndpoint(arg1) {
  return window['go']['main']['App']['ClassifyAIEndpoint'](arg1);
}

export function ComputeGaps(arg1) {
  return window['go']['main']['App']['ComputeGaps'](arg1);
}

export function ConnectGoogle(arg1, arg2) {
  return window['go']['main']['App']['ConnectGoogle'](arg1, arg2);
}

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function CreateGapFill(arg1) {
  return window['go']['main']['App']['CreateGapFill'](arg1);
}

export function CreateManualEvent(arg1) {
  return window['go']['main']['App']['CreateManualEvent'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteManualEvent(arg1) {
  return window['go']['main']['App']['DeleteManualEvent'](arg1);
}

export function DisconnectGoogle(arg1) {
  return window['go']['main']['App']['DisconnectGoogle'](arg1);
}

export function DiscoverLocalAIEndpoints() {
  return window['go']['main']['App']['DiscoverLocalAIEndpoints']();
}

export function EnsureCurrentPeriod(arg1, arg2) {
  return window['go']['main']['App']['EnsureCurrentPeriod'](arg1, arg2);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListAIModels(arg1, arg2) {
  return window['go']['main']['App']['ListAIModels'](arg1, arg2);
}

export function ListCalendars() {
  return window['go']['main']['App']['ListCalendars']();
}

export function ListCategories() {
  return window['go']['main']['App']['ListCategories']();
}

export function ListEvents(arg1) {
  return window['go']['main']['App']['ListEvents'](arg1);
}

export function ListGapFills(arg1) {
  return window['go']['main']['App']['ListGapFills'](arg1);
}

export function ListIntegrationConnections() {
  return window['go']['main']['App']['ListIntegrationConnections']();
}

export function ListOpenReviewItems(arg1) {
  return window['go']['main']['App']['ListOpenReviewItems'](arg1);
}

export function ListPeriods() {
  return window['go']['main']['App']['ListPeriods']();
}

export function ListSelectedCalendars() {
  return window['go']['main']['App']['ListSelectedCalendars']();
}

export function ListTzSegments(arg1) {
  return window['go']['main']['App']['ListTzSegments'](arg1);
}

export function ResolveReviewItem(arg1) {
  return window['go']['main']['App']['ResolveReviewItem'](arg1);
}

export function SaveAIConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveAIConfig'](arg1, arg2);
}

export function SaveAIEndpoint(arg1) {
  return window['go']['main']['App']['SaveAIEndpoint'](arg1);
}

export function SaveAIModel(arg1) {
  return window['go']['main']['App']['SaveAIModel'](arg1);
}

export function SaveExportFile(arg1, arg2) {
  return window['go']['main']['App']['SaveExportFile'](arg1, arg2);
}

export function SetCalendarDefaultCategory(arg1, arg2) {
  return window['go']['main']['App']['SetCalendarDefaultCategory'](arg1, arg2);
}

export function SetCalendarSelected(arg1, arg2) {
  return window['go']['main']['App']['SetCalendarSelected'](arg1, arg2);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SuggestGapFill(arg1) {
  return window['go']['main']['App']['SuggestGapFill'](arg1);
}

export function SyncPeriod(arg1) {
  return window['go']['main']['App']['SyncPeriod'](arg1);
}

export function UpdateCategory(arg1) {
  return window['go']['main']['App']['UpdateCategory'](arg1);
}

export function UpdateManualEvent(arg1) {
  return window['go']['main']['App']['UpdateManualEvent'](arg1);
}

export function ValidateAIConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['ValidateAIConfig'](arg1, arg2, arg3);
}
