// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClassifyAIEndpoint(arg1) {
  return window['go']['main']['App']['ClassifyAIEndpoint'](arg1);
}

export function ConnectGitHub(arg1) {
  return window['go']['main']['App']['ConnectGitHub'](arg1);
}

export function ConnectGoogle(arg1, arg2) {
  return window['go']['main']['App']['ConnectGoogle'](arg1, arg2);
}

export function ConnectSlack() {
  return window['go']['main']['App']['ConnectSlack']();
}

export function DisconnectGitHub(arg1) {
  return window['go']['main']['App']['DisconnectGitHub'](arg1);
}

export function DisconnectGoogle(arg1) {
  return window['go']['main']['App']['DisconnectGoogle'](arg1);
}

export function DisconnectSlack(arg1) {
  return window['go']['main']['App']['DisconnectSlack'](arg1);
}

export function DiscoverLocalAIEndpoints() {
  return window['go']['main']['App']['DiscoverLocalAIEndpoints']();
}

export function GetGoogleAuthStatus() {
  return window['go']['main']['App']['GetGoogleAuthStatus']();
}

export function GitHubAuthMode() {
  return window['go']['main']['App']['GitHubAuthMode']();
}

export function GitHubOAuthAvailable() {
  return window['go']['main']['App']['GitHubOAuthAvailable']();
}

export function ListAIModels(arg1, arg2) {
  return window['go']['main']['App']['ListAIModels'](arg1, arg2);
}

export function SaveAIConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveAIConfig'](arg1, arg2);
}

export function SaveAIEndpoint(arg1) {
  return window['go']['main']['App']['SaveAIEndpoint'](arg1);
}

export function SaveAIModel(arg1) {
  return window['go']['main']['App']['SaveAIModel'](arg1);
}

export function SaveExportFile(arg1, arg2) {
  return window['go']['main']['App']['SaveExportFile'](arg1, arg2);
}

export function SlackAuthMode() {
  return window['go']['main']['App']['SlackAuthMode']();
}

export function SlackOAuthAvailable() {
  return window['go']['main']['App']['SlackOAuthAvailable']();
}

export function ValidateAIConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['ValidateAIConfig'](arg1, arg2, arg3);
}
