// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {service} from '../models';
import {connection} from '../models';
import {ai} from '../models';

export function ClassifyAIEndpoint(arg1:string):Promise<main.AIClassification>;

export function ComputeGaps(arg1:number):Promise<Array<service.DayTimeline>>;

export function ConnectGoogle(arg1:string,arg2:string):Promise<connection.Connection>;

export function CreateCategory(arg1:service.CreateCategoryInput):Promise<service.Category>;

export function CreateGapFill(arg1:service.ManualEventInput):Promise<main.ManualEventResult>;

export function CreateManualEvent(arg1:service.ManualEventInput):Promise<main.ManualEventResult>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteManualEvent(arg1:service.ManualEventDeleteInput):Promise<main.ManualEventResult>;

export function DisconnectGoogle(arg1:string):Promise<void>;

export function DiscoverLocalAIEndpoints():Promise<Array<ai.Endpoint>>;

export function EnsureCurrentPeriod(arg1:string,arg2:string):Promise<service.Period>;

export function ExcludeEvent(arg1:service.ExcludeEventInput):Promise<service.ExcludeEventResult>;

export function GetSetting(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListAIModels(arg1:string,arg2:string):Promise<Array<string>>;

export function ListCalendars():Promise<Array<service.Calendar>>;

export function ListCategories():Promise<Array<service.Category>>;

export function ListEventCategoryOverlays(arg1:number):Promise<Array<service.EventCategoryOverlay>>;

export function ListEvents(arg1:number):Promise<Array<service.Event>>;

export function ListGapFills(arg1:number):Promise<Array<service.GapFill>>;

export function ListIntegrationConnections():Promise<Array<connection.Connection>>;

export function ListOpenReviewItems(arg1:number):Promise<Array<service.ReviewItem>>;

export function ListPeriods():Promise<Array<service.Period>>;

export function ListSelectedCalendars():Promise<Array<service.Calendar>>;

export function ListTzSegments(arg1:number):Promise<Array<service.TzSegment>>;

export function ResolveReviewItem(arg1:service.ResolveReviewItemInput):Promise<service.ResolveReviewItemResult>;

export function SaveAIConfig(arg1:string,arg2:string):Promise<void>;

export function SaveAIEndpoint(arg1:string):Promise<void>;

export function SaveAIModel(arg1:string):Promise<void>;

export function SaveExportFile(arg1:string,arg2:string):Promise<string>;

export function SetCalendarDefaultCategory(arg1:number,arg2:any):Promise<void>;

export function SetCalendarSelected(arg1:number,arg2:boolean):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SuggestGapFill(arg1:service.TimeWindow):Promise<service.GapSuggestion>;

export function SyncPeriod(arg1:number):Promise<service.SyncResult>;

export function UpdateCategory(arg1:service.UpdateCategoryInput):Promise<service.Category>;

export function UpdateManualEvent(arg1:service.ManualEventUpdateInput):Promise<main.ManualEventResult>;

export function ValidateAIConfig(arg1:string,arg2:string,arg3:string):Promise<ai.ValidationResult>;
