// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {main} from '../models';
import {ai} from '../models';

export function ComputeGaps(arg1:number):Promise<Array<service.DayTimeline>>;

export function ClassifyAIEndpoint(arg1:string):Promise<main.AIClassification>;

export function CreateManualEvent(arg1:service.ManualEventInput):Promise<main.ManualEventResult>;

export function DeleteManualEvent(arg1:service.ManualEventDeleteInput):Promise<main.ManualEventResult>;

export function DiscoverLocalAIEndpoints():Promise<Array<ai.Endpoint>>;

export function EnsureCurrentPeriod(arg1:string,arg2:string):Promise<service.Period>;

export function GetSetting(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListAIModels(arg1:string,arg2:string):Promise<Array<string>>;

export function ListCalendars():Promise<Array<service.Calendar>>;

export function ListCategories():Promise<Array<service.Category>>;

export function ListEvents(arg1:number):Promise<Array<service.Event>>;

export function ListGapFills(arg1:number):Promise<Array<service.GapFill>>;

export function ListOpenReviewItems(arg1:number):Promise<Array<service.ReviewItem>>;

export function ListPeriods():Promise<Array<service.Period>>;

export function ListSelectedCalendars():Promise<Array<service.Calendar>>;

export function ListTzSegments(arg1:number):Promise<Array<service.TzSegment>>;

export function SaveAIConfig(arg1:string,arg2:string):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function UpdateManualEvent(arg1:service.ManualEventUpdateInput):Promise<main.ManualEventResult>;

export function ValidateAIConfig(arg1:string,arg2:string,arg3:string):Promise<ai.ValidationResult>;
